	SUBROUTINE SET_IDISP_ISEND(IDISP,ISEND,ND,NTHREAD)
	IMPLICIT NONE
	INTEGER ND
	INTEGER NTHREAD
	INTEGER IDISP(0:NTHREAD-1)
	INTEGER ISEND(0:NTHREAD-1)
!
	INTEGER NDEPTHS_MIN
	INTEGER REM
	INTEGER K
!
	NDEPTHS_MIN=ND/NTHREAD
	REM=MOD(ND,NTHREAD)
	DO K=0,NTHREAD-1
	  IDISP(K)=K*NDEPTHS_MIN+MIN(K,REM)
	  ISEND(K)=NDEPTHS_MIN+MIN(K+1,REM)-MIN(K,REM)
	END DO
!
	RETURN
	END
!
	SUBROUTINE SET_DST_DEND(DST,DEND,ND,NTHREAD, MYPE)
	IMPLICIT NONE
!
	INTEGER DST,DEND,ND,NTHREAD
	INTEGER MYPE
	INTEGER NDEPTHS_MIN
	INTEGER REM
!
	NDEPTHS_MIN=ND/NTHREAD
	REM=MOD(ND,NTHREAD)
	DST=1+MYPE*NDEPTHS_MIN+MIN(MYPE,REM)
	DEND=(MYPE+1)*NDEPTHS_MIN+MIN(MYPE+1,REM)
!
	RETURN
	END	
