	PROGRAM TST_THREAD_ASS
	IMPLICIT NONE
!
	INTEGER, ALLOCATABLE :: IDISP(:),ISEND(:)
	INTEGER ND
	INTEGER DST,DEND
	INTEGER NTHREAD
	INTEGER K
	INTEGER REM
!
	WRITE(6,'(A)',ADVANCE='NO')'Input ND, NTHREADS:'
	READ(5,*)ND,NTHREAD
	ALLOCATE(IDISP(0:NTHREAD-1))
	ALLOCATE(ISEND(0:NTHREAD-1))
!!
	CALL SET_IDISP_ISEND(IDISP,ISEND,ND,NTHREAD)
	DO K=0,NTHREAD-1
	  CALL SET_DST_DEND(DST,DEND,ND,NTHREAD,K)
	  WRITE(6,*)K, DST, DEND, DEND-DST+1, IDISP(K), ISEND(K)
	END DO
!
	STOP
	END
