	SUBROUTINE WR_COOL_MPI_V1(AD_COOL_V,AD_COOL_DT,ARTIFICIAL_HEAT_TERM,
	1                dE_RAD_DECAY,dE_SHOCK_POWER,
	1                XRAY_LUM_TOT,INCL_ADIABATIC,ND)
        USE SET_KIND_MODULE
        USE MPI
	USE MOD_CMFGEN
	IMPLICIT NONE
!
	INTEGER ND
	REAL(KIND=LDP) AD_COOL_V(DST:DEND)
	REAL(KIND=LDP) AD_COOL_DT(DST:DEND)
	REAL(KIND=LDP) dE_RAD_DECAY(DST:DEND)
	REAL(KIND=LDP) dE_SHOCK_POWER(DST:DEND)
	REAL(KIND=LDP) XRAY_LUM_TOT(DST:DEND)
	REAL(KIND=LDP) ARTIFICIAL_HEAT_TERM(DST:DEND)
	LOGICAL INCL_ADIABATIC
!
	REAL(KIND=LDP) LOC_AD_COOL_V(ND)
	REAL(KIND=LDP) LOC_AD_COOL_DT(ND)
	REAL(KIND=LDP) LOC_dE_RAD_DECAY(ND)
	REAL(KIND=LDP) LOC_dE_SHOCK_POWER(ND)
	REAL(KIND=LDP) LOC_ARTIFICIAL_HEAT_TERM(ND)
!
	REAL(KIND=LDP) NETCR(ND)
	REAL(KIND=LDP) TOTCR(ND)
	REAL(KIND=LDP) XRAY_HEATING(ND)
	INTEGER ISEND(0:NTHREAD-1)
	INTEGER IDISP(0:NTHREAD-1)
!
	INTEGER I,K,LS,ML
	INTEGER ID
	INTEGER LU
	INTEGER, PARAMETER :: IZERO=0
	LOGICAL, PARAMETER :: L_FALSE=.FALSE.
	CHARACTER(LEN=80) TMP_STRING
!
!	include 'mpif.h'
!
	CALL GET_LU(LU,'In WR_COOL_MPI_V1')
	DO ID=1,NUM_IONS
          IF(ATM(ID)%XzV_PRES)THEN
	    CALL SET_IDISP_ISEND(IDISP,ISEND,ND,NTHREAD)
            IDISP=IDISP*ATM(ID)%NXzV
            ISEND=ISEND*ATM(ID)%NXzV
            CALL MPI_GATHERV(ATM(ID)%BFCRXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%BFCRXzV,ISEND,IDISP,
	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
!
	    CALL SET_IDISP_ISEND(IDISP,ISEND,ND,NTHREAD)
	    CALL MPI_GATHERV(ATM(ID)%FFXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%FFXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%COOLXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%COOLXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%DIECOOL,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%DIECOOL,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%X_COOL,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%X_COOL,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%NTCXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%NTCXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%FFXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%FFXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%FFXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%FFXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%FFXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%FFXzV,ISEND,IDISP,
	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(dE_RAD_DECAY,ISEND(MYPE),MPI_DOUBLE_PRECISION,LOC_dE_RAD_DECAY,ISEND,IDISP,
	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(dE_SHOCK_POWER,ISEND(MYPE),MPI_DOUBLE_PRECISION,LOC_dE_SHOCK_POWER,ISEND,IDISP,
	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(AD_COOL_V,ISEND(MYPE),MPI_DOUBLE_PRECISION,LOC_AD_COOL_V,ISEND,IDISP,
	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(AD_COOL_DT,ISEND(MYPE),MPI_DOUBLE_PRECISION,LOC_AD_COOL_DT,ISEND,IDISP,
	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
!	    CALL MPI_GATHERV(XRAY_HEATING,ISEND(MYPE),MPI_DOUBLE_PRECISION,LOC_XRAY_HEATING,ISEND,IDISP,
!	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ARTIFICIAL_HEAT_TERM,ISEND(MYPE),MPI_DOUBLE_PRECISION,LOC_ARTIFICIAL_HEAT_TERM,ISEND,IDISP,
	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	  END IF
	END DO
!
! This routin gathers the charge exchange cooling rates for later writing.
!
	CALL READY_CHG_COOL_WR(ND)

	IF(MYPE .NE. 0)RETURN
!
! We use TA for NETCR (the net cooling rate).
! We use TB for TOTCR (the sum[absolute cooling rates]).
!
	DO ML=1,(ND+9)/10
	  LS=ML
	  CALL FSTCOOL_V3(R,V,T,ED,NETCR,TOTCR,LS,ND,LU)
	  DO ID=1,NUM_IONS-1
	    IF(ATM(ID)%XzV_PRES)THEN
	      CALL WRCOOLGEN_V3(ROOT(ID)%BFCRXzV, ROOT(ID)%FFXzV, ROOT(ID)%COOLXzV,
	1           ROOT(ID)%DIECOOL, ROOT(ID)%X_COOL, ROOT(ID)%NTCXzV,
	1           ATM(ID)%XzV_PRES, ATM(ID)%NXzV, ION_ID(ID),
	1           NETCR,TOTCR,LS,ND,LU)
	    END IF
	  END DO
!
! Output adiabatic cooling rate.
!
	  CALL WR_AD_COOL(LOC_AD_COOL_V,LOC_AD_COOL_DT,NETCR,TOTCR,INCL_ADIABATIC,LS,ND,LU)
!
! Output charge exchange cooling rate, radioactive heating team
! (hence option L_FALSE), and artificial heating term.
!
	  CALL WR_CHG_COOL_MPI_V1(NETCR,TOTCR,LS,ND,LU)
	  CALL WR_COOLING_TERM(LOC_dE_SHOCK_POWER,NETCR,TOTCR,L_FALSE,'Shock Power Term',LS,ND,LU)
	  CALL WR_COOLING_TERM(LOC_dE_RAD_DECAY,NETCR,TOTCR,L_FALSE,'Radiative decay heating term',LS,ND,LU)
!          XRAY_HEATING(1:ND)=4.0E-10_LDP*3.1459_LDP*XRAY_LUM_TOT(1:ND)/CLUMP_FAC(1:ND)
!	  CALL WR_COOLING_TERM(XRAY_HEATING,NETCR,TOTCR,L_FALSE,'X-ray heating term',LS,ND,LU)
	  CALL WR_ART_HEAT(LOC_ARTIFICIAL_HEAT_TERM,NETCR,TOTCR,LS,ND,LU)
!
	  CALL ENDCOOL_V3(NETCR,TOTCR,LS,ND,LU)
	END DO
!
	RETURN
	END	
