	SUBROUTINE WR_COOL_MPI_V1(X_RAY_LUM_TOT,ND)
        USE SET_KIND_MODULE
        USE MOD_CMFGEN
!
	INTEGER ND
	REAL(KIND=LDP) XRAY_LUM_TOT(ND)
	REAL(KIND=LDP) NETCR(ND)
	REAL(KIND=LDP) TOTCR(ND)
	REAL(KIND=LDP) XRAY_HEATING(ND)
	INTEGER ISEND(0:NTHREAD-1)
	INTEGER IDISP(0:NTHREAD-1)
	INTEGER ID
	INTEGER, PARAMETER :: IZERO=0
	CHARACTER(LEN=80) TMP_STRING
!
	DO ID=1,NUM_IONS
          IF(ATM(ID)%XzV_PRES)THEN
            K=(DEND-DST+1)
            DO I=0,NTHREAD-1
              IDISP(I)=I*K*ND*ATM(ID)%NXzV
              ISEND(I)=(DEND-DST+1)*ATM(ID)%NXzV
            END DO
            CALL MPI_GATHERV(ATM(ID)%BFCRXzV,ISEND(MPYE),MPI_DOUBLE_PRECISION,ROOT(ID)%BFCRXzV,ISEND,IDISP,
	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
!
            K=(DEND-DST+1)
            DO I=0,NTHREAD-1
              IDISP(I)=I*K*ND
              ISEND(I)=(DEND-DST+1)
            END DO
	    CALL MPI_GATHERV(ATM(ID)%FFXzV,ISEND(MPYE),MPI_DOUBLE_PRECISION,ROOT(ID)%FFXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%COOLXzV,ISEND(MPYE),MPI_DOUBLE_PRECISION,ROOT(ID)%COOLXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%DIECOOL,ISEND(MPYE),MPI_DOUBLE_PRECISION,ROOT(ID)%DIECOOL,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%X_COOL,ISEND(MPYE),MPI_DOUBLE_PRECISION,ROOT(ID)%X_COOL,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%NTCXzV,ISEND(MPYE),MPI_DOUBLE_PRECISION,ROOT(ID)%NTCXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%FFXzV,ISEND(MPYE),MPI_DOUBLE_PRECISION,ROOT(ID)%FFXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%FFXzV,ISEND(MPYE),MPI_DOUBLE_PRECISION,ROOT(ID)%FFXzV,ISEND,IDISP,
	1	             MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%FFXzV,ISEND(MPYE),MPI_DOUBLE_PRECISION,ROOT(ID)%FFXzV,ISEND,IDISP,
	1                     MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	  END IF
	END DO
!
	IF(MYPE .EQ. 0)RETURN
!
! We use TA for NETCR (the net cooling rate).
! We use TB for TOTCR (the sum[absolute cooling rates]).
!
	DO ML=1,(ND+9)/10
	  LS=ML
	  CALL FSTCOOL_V3(R,V,T,ED,NETCR,TOTCR,LS,ND,LU_REC_CHK)
	  DO ID=1,NUM_IONS-1
	    IF(ATM(ID)%XzV_PRES)THEN
	      CALL WRCOOLGEN_V3(ROOT(ID)%BFCRXzV, ROOT(ID)%FFXzV, ROOT(ID)%COOLXzV,
	1           ROOT(ID)%DIECOOL, ROOT(ID)%X_COOL, ROOT(ID)%NTCXzV,
	1           ATM(ID)%XzV_PRES, ATM(ID)%NXzV, ION_ID(ID),
	1           NETCR,TOTCR,LS,ND,LU_REC_CHK)
	    END IF
	  END DO
!
! Output adiabatic cooling rate.
!
	  CALL WR_AD_COOL(AD_COOL_V,AD_COOL_DT,NETCR,TOTCR,
	1            INCL_ADIABATIC,LS,ND,LU_REC_CHK)
!
! Output charge exchange cooling rate, radioactive heating team
! (hence option L_FALSE), and artificial heating term.
!
	  CALL WR_CHG_COOL_V3(NETCR,TOTCR,LS,ND,LU_REC_CHK)
	  CALL WR_COOLING_TERM(dE_SHOCK_POWER,NETCR,TOTCR,L_FALSE,
	1             'Shock Power Term',LS,ND,LU_REC_CHK)
	  CALL WR_COOLING_TERM(dE_RAD_DECAY,NETCR,TOTCR,L_FALSE,
	1             'Radiative decay heating term',LS,ND,LU_REC_CHK)
          XRAY_HEATING(1:ND)=4.0E-10_LDP*3.1459_LDP*XRAY_LUM_TOT(1:ND)/CLUMP_FAC(1:ND)
	  CALL WR_COOLING_TERM(XRAY_HEATING,NETCR,TOTCR,L_FALSE,
	1             'X-ray heating term',LS,ND,LU_REC_CHK)
	  CALL WR_ART_HEAT(ARTIFICIAL_HEAT_TERM,NETCR,TOTCR,LS,ND,LU_REC_CHK)
!
	  CALL ENDCOOL_V3(NETCR,TOTCR,LS,ND,LU_REC_CHK)
	END DO
!
	RETURN
	END	
