	SUBROUTINE WRITE_RECOM_MPI_V1(ND)
	USE SET_KIND_MODULE
        USE MPI
	USE MOD_CMFGEN
	USE STEQ_DATA_MOD
	IMPLICIT NONE
!
! Altered: 28-Oct-2025: Recombination rate now computed with respect to total ion population.
!                       This fixes a diagnostic issue when the lower term is split.
!                       Fixed bug created when merging galah and CRC versions.
! Altered: 13-Aug-2025: LOC_STEQ_ADV now only defined for MYPE=0
!
	INTEGER ND
	REAL(KIND=LDP) LOC_X(ND)
	REAL(KIND=LDP) LOC_NT_2E(ND)
	REAL(KIND=LDP), ALLOCATABLE :: LOC_STEQ_ADV(:,:)
	REAL(KIND=LDP), ALLOCATABLE :: TMP_ION(:)
	INTEGER ID, I, K
	INTEGER LU
	INTEGER SCAT_SIZE(0:NTHREAD-1)
	INTEGER SCAT_DISP(0:NTHREAD-1)
	INTEGER, PARAMETER :: IZERO=0
	CHARACTER(LEN=80) TMP_STRING
!
!
! Write out recombination, photoionization and cooling terms for digestion.
!
! Since X_RECOM (and X_COOL) were dimensioned (ND,0:NION), and since it was
! initialized, we can assume X_RECOM(1,0) is zero, and hence it can be used
! as a  dummy vector for the special case when ATM(ID-1)%INDX=0.
!
! NB: For the first ionization stage of a species, ATM(ID-1)%INDX will
!     refer to the highest level of the previous ion.  By convention in
!     CMFGEN this refers to a 1 level state with an INDEX of 0 (and
!     XzV_PRES for this species is FALSE).
!
! LOC_STEQ_ADV gets the data from all processes, and only needs to be defined on MYPE=0
!
	IF(MYPE .EQ. 0)THEN
 	  ALLOCATE(LOC_STEQ_ADV(ND,NUM_IONS)); LOC_STEQ_ADV=0.0_LDP
	  ALLOCATE(TMP_ION(ND))
	END IF
!
	CALL GET_LU(LU,'In WRITE_RECOM_MPI_V1')
	DO ID=1,NUM_IONS
	  IF(ATM(ID)%XzV_PRES)THEN
	    CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	    SCAT_DISP=SCAT_DISP*ATM(ID)%NXzV
	    SCAT_SIZE=SCAT_SIZE*ATM(ID)%NXzV
!
	    CALL MPI_GATHERV(ATM(ID)%APRXzV,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%APRXzV,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%ARRXzV,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%ARRXzV,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
!
	    CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	    CALL MPI_GATHERV(ATM(ID)%CPRXzV,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%CPRXzV,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%CRRXzV,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%CRRXzV,
	1	                SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
!
	    CALL MPI_GATHERV(ATM(ID)%CHG_PRXzV,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%CHG_PRXzV,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%CHG_RRXzV,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%CHG_RRXzV,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%NTIXzV,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%NTIXzV,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%NTIXzV_2E,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%NTIXzV_2E,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
!
	    CALL MPI_GATHERV(ATM(ID)%DIERECOM,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%DIERECOM,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%ADDRECOM,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%ADDRECOM,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%X_RECOM,SCAT_SIZE(MYPE),MY_MPI_DP,ROOT(ID)%X_RECOM,
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(SE(ID)%STEQ_ADV,SCAT_SIZE(MYPE),MY_MPI_DP,LOC_STEQ_ADV(1,ID),
	1                       SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	  END IF
	END DO
!
! Only root needs to WRITE the files.
!
	IF(MYPE .NE. 0)RETURN
	DO ID=1,NUM_IONS-1
	  IF(ATM(ID)%XzV_PRES)THEN
	    LOC_X=0.0_LDP; LOC_NT_2E=0.0_LDP
	    IF(ID .NE. 1)THEN
	      LOC_X=ROOT(ID-1)%X_RECOM
	      IF(ATM(ID-1)%XzV_PRES)THEN
	        LOC_NT_2E=ROOT(ID-1)%NTIXzV_2E
	      END IF
	    END IF
	    IF(ATM(ID+1)%XzV_PRES)THEN
	      TMP_ION=0.0D0
	      DO I=1,ND
	        DO K=1,ATM(ID+1)%NXzV
	          TMP_ION(I)=TMP_ION(I)+ROOT(ID+1)%XzV(K,I)
	        END DO
	      END DO
	    ELSE
	      TMP_ION=ROOT(ID)%DXzV
	    END IF
	    TMP_STRING=TRIM(ION_ID(ID))//'PRRR'
	    CALL WRRECOMCHK_MPI_V1(ROOT(ID)%APRXzV, ROOT(ID)%ARRXzV,
	1          ROOT(ID)%CPRXzV, ROOT(ID)%CRRXzV,
	1          ROOT(ID)%CHG_PRXzV, ROOT(ID)%CHG_RRXzV, LOC_STEQ_ADV(:,ID),
	1          ROOT(ID)%DIERECOM,  ROOT(ID)%ADDRECOM,
	1          LOC_X, ROOT(ID)%X_RECOM,
	1          ROOT(ID)%NTIXzV,LOC_NT_2E, ROOT(ID)%NTIXzV_2E,
	1          R,T,ED,TMP_ION,ATM(ID)%NXzV,
	1          ND,LU,TMP_STRING,ION_ID,ID)
	  END IF
!
	END DO
!
	DEALLOCATE (TMP_ION,LOC_STEQ_ADV)
	RETURN
	END
