	SUBROUTINE WRITE_RECOM_MPI_V1(ND)
	USE SET_KIND_MODULE
        USE MOD_CMFGEN
	USE STEQ_DATA_MOD
	IMPLICIT NONE
!
	INTEGER ND
	REAL(KIND=LDP) LOC_X(ND)
	REAL(KIND=LDP) LOC_NT_2E(ND)
	INTEGER ID, I, K
	INTEGER LU
	INTEGER ISEND(0:NTHREAD-1)
	INTEGER IDISP(0:NTHREAD-1)
	INTEGER, PARAMETER :: IZERO=0
	CHARACTER(LEN=80) TMP_STRING
        INCLUDE 'mpif.h'
!
! Write out recombination, photoionization and cooling terms for digestion.
!
! Since X_RECOM (and X_COOL) were dimensioned (ND,0:NION), and since it was
! initialized, we can assume X_RECOM(1,0) is zero, and hence it can be used
! as a  dummy vector for the special case when ATM(ID-1)%INDX=0.
!
! NB: For the first ionization stage of a species, ATM(ID-1)%INDX will
!     refer to the highest level of the previous ion.  By convention in
!     CMFGEN this refers to a 1 level state with an INDEX of 0 (and
!     XzV_PRES for this species is FALSE).
!
	CALL GET_LU(LU,'In WRITE_RECOM_MPI_V1')
	DO ID=1,NUM_IONS
	  IF(ATM(ID)%XzV_PRES)THEN
	    K=(DEND-DST+1)
	    DO I=0,NTHREAD-1
	      IDISP(I)=I*K*ND*ATM(ID)%NXzV
	      ISEND(I)=(DEND-DST+1)*ATM(ID)%NXzV
	    END DO
	    CALL MPI_GATHERV(ATM(ID)%APRXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%APRXzV,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%ARRXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%ARRXzV,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%CPRXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%CPRXzV,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%CRRXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%CRRXzV,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%CHG_PRXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%CHG_PRXzV,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%CHG_RRXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%CHG_RRXzV,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%NTIXzV,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%NTIXzV,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%NTIXzV_2E,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%NTIXzV_2E,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
!
	    K=(DEND-DST+1)
	    DO I=0,NTHREAD-1
	      IDISP(I)=I*K*ND
	      ISEND(I)=(DEND-DST+1)
	    END DO
	    CALL MPI_GATHERV(ATM(ID)%DIERECOM,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%DIERECOM,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%ADDRECOM,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%ADDRECOM,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	    CALL MPI_GATHERV(ATM(ID)%X_RECOM,ISEND(MYPE),MPI_DOUBLE_PRECISION,ROOT(ID)%X_RECOM,ISEND,IDISP,
	1                    MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	  END IF
	END DO
!
! Only root needs to WRITE the files.
!
	IF(MYPE .NE. 0)RETURN
	DO ID=1,NUM_IONS-1
	  IF(ATM(ID)%XzV_PRES)THEN
	    LOC_X=0.0_LDP; LOC_NT_2E=0.0_LDP
	    IF(ID .NE. 1)THEN
	      LOC_X=ATM(ID-1)%X_RECOM
	      IF(ATM(ID-1)%XzV_PRES)THEN
	        LOC_NT_2E=ROOT(ID-1)%NTIXzV_2E
	      END IF
	    END IF
	    TMP_STRING=TRIM(ION_ID(ID))//'PRRR'
	    CALL WRRECOMCHK_MPI_V1(ROOT(ID)%APRXzV, ROOT(ID)%ARRXzV,
	1          ROOT(ID)%CPRXzV, ROOT(ID)%CRRXzV,
	1          ROOT(ID)%CHG_PRXzV, ROOT(ID)%CHG_RRXzV, SE(ID)%STEQ_ADV,
	1          ROOT(ID)%DIERECOM,  ROOT(ID)%ADDRECOM,
	1          LOC_X, ROOT(ID)%X_RECOM,
	1          ROOT(ID)%NTIXzV,LOC_NT_2E, ROOT(ID)%NTIXzV_2E,
	1          R,T,ED,ROOT(ID)%DXzV,ATM(ID)%NXzV,
	1          ND,LU,TMP_STRING,ION_ID,ID)
	  END IF
	END DO
!
	RETURN
	END
