	SUBROUTINE ACCEL_TRI_SOL_IT(CUR_EST,DST,DEND,ND,NT,IT_COUNTER,NG_CNT)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER NT
	INTEGER IT_COUNTER
	INTEGER NG_CNT
	INTEGER DST,DEND,ND
	INTEGER IERR
	INTEGER, PARAMETER :: IZERO=0.0_LDP
!
	REAL(KIND=LDP) CUR_EST(NT,DST:DEND)
!
! Local variables
!
	REAL(KIND=LDP), ALLOCATABLE,SAVE :: STORE(:,:,:)
	REAL(KIND=LDP), ALLOCATABLE :: REV_EST(:,:)
	INTEGER, ALLOCATABLE :: SCAT_DISP(:),SCAT_SIZE(:)
!
	IF(MYPE .EQ. 0 .AND. .NOT. ALLOCATED(STORE))THEN
	   ALLOCATE(STORE(NT,ND,4))
	END IF
!
	IF(MOD(IT_COUNTER+3,NG_CNT) .EQ. 0)THEN
	  CALL GATHER_MAT_TO_ROOT_MPI_V1(CUR_EST,DST,DEND,STORE(:,:,4),NT,ND)
	ELSE IF(MOD(IT_COUNTER+2,NG_CNT) .EQ. 0)THEN
	  CALL GATHER_MAT_TO_ROOT_MPI_V1(CUR_EST,DST,DEND,STORE(:,:,3),NT,ND)
	ELSE IF(MOD(IT_COUNTER+1,NG_CNT) .EQ. 0)THEN
	  CALL GATHER_MAT_TO_ROOT_MPI_V1(CUR_EST,DST,DEND,STORE(:,:,2),NT,ND)
	ELSE IF(MOD(IT_COUNTER,NG_CNT) .EQ. 0)THEN
	  CALL GATHER_MAT_TO_ROOT_MPI_V1(CUR_EST,DST,DEND,STORE(:,:,1),NT,ND)
	   IF(MYPE .EQ. 0)THEN
	     ALLOCATE(REV_EST(NT,ND))
	   END IF
	   IF(MYPE .EQ. 0)THEN
	     CALL NGACCEL(REV_EST,STORE,ND*NT,.FALSE.)
	   END IF
	   ALLOCATE (SCAT_DISP(0:NTHREAD-1),SCAT_SIZE(0:NTHREAD-1))
	   CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	   CALL MPI_SCATTERV(REV_EST,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,
	1            CUR_EST,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	   IF(MYPE .EQ. 0)DEALLOCATE(REV_EST,SCAT_DISP,SCAT_SIZE)
	END IF
!
	RETURN
	END
