	SUBROUTINE CHECK_HYD(R,V,T,MASS_DENSITY,POP_ATOM,ED,P,GAMMA_FULL,BC,MU_ATOM,ND,LS)
	USE SET_KIND_MOD
	IMPLICIT NONE
	INTEGER ND
!
	REAL(KIND=LDP) R(ND)
	REAL(KIND=LDP) V(ND)
	REAL(KIND=LDP) T(ND)
	REAL(KIND=LDP) POP_ATOM(ND)
	REAL(KIND=LDP) ED(ND)
	REAL(KIND=LDP) P(ND)
	REAL(KIND=LDP) GAMMA_FULL(ND)
	REAL(KIND=LDP) MASS_DENSITY(ND)
!
	REAL(KIND=LDP) TA(ND)
	REAL(KIND=LDP) ASQ(ND)
	REAL(KIND=LDP) dvdR(ND)
	REAL(KIND=LDP) dpdR_EST(ND)
	REAL(KIND=LDP) COEDF(ND,4)
!
	TA=ED/POP_ATOM
	ASQ=BC*T*(1.0_LDP+TA)/MU_ATOM/AMU
!
	CALL MON_INT_FUNS_V2(COEF,TA,R,ND)
!
	dasq_a=ASQ/((1.0_LDP+TA)*COEF(:,3)

	CALL MON_INT_FUNS_V2(COEF,T,R,ND)
	dasq_t=ASQ*COEF(:,3)/T
!
	CALL MON_INT_FUNS_V2(COEF,V,R,ND)
        dVDR=COEF(:,3)
!
	dPdR_EST=dASQ_dg + dASQ_dT - 2*ASQ/R+ -ASQ*dVdR/V
!
	CALL MON_INT_FUNS_V2(COEF,O,R,ND)
        dpdR=COEF(:,3)/MASS_DENSITY
!
	DO I=1,ND
	  WRITE(LU,)I,R(I),V(I),T(I),ASQ(I),dASQ_dT(I),dASQ_dg(I),dPdR_EST(I),dPdR(I)
	END DPO
!
	RETURN
	END
	

