	SUBROUTINE CHECK_MPI_EQUALITY(VECTOR,N,MESSAGE)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER N
	REAL(KIND=LDP) VECTOR(N)
	CHARACTER(LEN=*) MESSAGE
!
	REAL(KIND=LDP) WORK(N)
	INTEGER ML
	LOGICAL NO_MATCH
	INTEGER, PARAMETER :: IZERO=0
	INTEGER, PARAMETER :: IONE=1
	INTEGER IERR
	INTEGER NCHK
!
	NO_MATCH=.FALSE.
	IF(MYPE .EQ. 0)NCHK=N
	CALL MPI_BCAST(NCHK,IONE,MPI_INTEGER,IZERO,MPI_COMM_WORLD,IERR)
	IF(NCHK .NE. N)THEN
	   NO_MATCH=.TRUE.
	   WRITE(6,*)'Invalid vector lengths',N,NCHK,MYPE
	   WRITE(6,*)TRIM(MESSAGE)
	END IF
	CALL MPI_ALLREDUCE(MPI_IN_PLACE,NO_MATCH,IONE,MPI_LOGICAL,MPI_LOR,MPI_COMM_WORLD,IERR)
	IF(NO_MATCH)THEN
	  CALL MPI_ERR_CHECK(1,'BAD vector lengths')
	  CALL MPI_FINALIZE(IERR)
	  STOP
	END IF
!
	IF(MYPE .EQ. 0)WORK=VECTOR
	CALL MPI_BCAST(WORK,N,MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	NO_MATCH=.FALSE.
	DO ML=1,N
	  IF(WORK(N) .NE. VECTOR(N))THEN
	    IF(.NOT. NO_MATCH)THEN
	       NO_MATCH=.TRUE.
	       WRITE(6,*)'Error -- vectors of different processes do not match',MYPE
	       WRITE(6,*)TRIM(MESSAGE)
	       WRITE(6,*)N
	    END IF
	    WRITE(6,*)ML,VECTOR(ML),WORK(ML)
	  END IF
	END DO
	CALL MPI_ALLREDUCE(MPI_IN_PLACE,NO_MATCH,IONE,MPI_LOGICAL,MPI_LOR,MPI_COMM_WORLD,IERR)
	IF(NO_MATCH)THEN
	  CALL MPI_ERR_CHECK(1,'BAD matching vectors')
	  CALL MPI_FINALIZE(IERR)
	  STOP
	END IF
!
	RETURN
	END
