	SUBROUTINE CHECK_EQ_IN_BA(NT,DESC)
	USE SET_KIND_MODULE
	USE STEQ_DATA_MOD
	USE MOD_CMFGEN
!
	INTEGER NT
	CHARACTER(LEN=*) DESC
!
	INTEGER ID
	INTEGER ISPEC
	INTEGER I
	INTEGER EQ
!
!	WRITE(6,*)'Checking ',MYPE,TRIM(DESC); FLUSH(UNIT=6)
	DO ISPEC=1,NUM_SPECIES
          DO ID=SPECIES_BEG_ID(ISPEC),SPECIES_END_ID(ISPEC)-1
            DO I=1,SE(ID)%N_SE-1
              EQ=SE(ID)%EQ_IN_BA(I)
              IF(ABS(EQ) .GT. NT)THEN
	        WRITE(6,*)TRIM(DESC)
	        WRITE(6,*)'MYPE,ISPEC,ID,I,EQ=',MYPE,ISPEC,ID,I,EQ; FLUSH(UNIT=6)
                STOP
	      END IF
	    END DO
          END DO
        END DO
!
	RETURN
	END

