	SUBROUTINE CREATE_CORRECTION_SUM_MPI_V1(SOL_MAT,DECREASE,INCREASE,MAX_dT_COR,IDEC,IINC,DST,DEND,ND,NT)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER ND,NT
	INTEGER DST,DEND
	INTEGER IDEC,IINC
	REAL(KIND=LDP) SOL_MAT(NT,DST:DEND)
	REAL(KIND=LDP) DECREASE,INCREASE
	REAL(KIND=LDP) MAX_dT_COR
!
	REAL(KIND=LDP) T1,T2
	INTEGER NUM_DEPTHS_PER_THREAD,IERR
	INTEGER COUNT(7)
	INTEGER I,J,K
	INTEGER IOS,LU_SUM
	INTEGER, PARAMETER :: IZERO=0
	INTEGER, PARAMETER :: IONE=1
	INTEGER, ALLOCATABLE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE :: SCAT_SIZE(:)
!
	CHARACTER(LEN=80), ALLOCATABLE ::  LOC_STRING(:)
	CHARACTER(LEN=80), ALLOCATABLE :: STRING(:)
!
!	include 'mpif.h'
!
	ALLOCATE(LOC_STRING(DST:DEND)); LOC_STRING=' '
	ALLOCATE (SCAT_DISP(0:NTHREAD-1),SCAT_SIZE(0:NTHREAD-1))
!	
!   SOL_MAT is +ve when the populations are to decrease.
!   SOL_MAT is -ve when the populations are to increase.
!
	DECREASE=0.0_LDP; INCREASE=0.0_LDP
	IDEC=0; IINC=0
	DO I=DST,DEND
	  COUNT(:)=0
	  DO J=1,NT
	    IF(SOL_MAT(J,I) .GT. DECREASE)THEN
	      DECREASE=SOL_MAT(J,I)
	      IDEC=I
	    ELSE IF(SOL_MAT(J,I) .LT. INCREASE)THEN
	      INCREASE=SOL_MAT(J,I)
	      IINC=I
	    END IF
	    T1=1.0E+06_LDP*ABS(SOL_MAT(J,I))+1.0E-31_LDP		!to ensure non-zero.
	    K=LOG10(T1)+1; K=MIN(7,K)
	    IF(K > 0)COUNT(1:K)=COUNT(1:K)+1
	  END DO
	  MAX_dT_COR=MAX(MAX_dT_COR,ABS(SOL_MAT(NT,I)))
	  WRITE(LOC_STRING(I),'(8I8)')I,COUNT(7:1:-1)
	  K=80
	END DO
!
	T1=DECREASE; CALL MPI_ALLREDUCE(T1,DECREASE,IONE,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERR)
	IF(DECREASE .NE. T1)IDEC=0
	I=IDEC; CALL MPI_ALLREDUCE(I,IDEC,IONE,MPI_INTEGER,MPI_MAX,MPI_COMM_WORLD,IERR)
!
	T1=INCREASE; CALL MPI_ALLREDUCE(T1,INCREASE,IONE,MPI_DOUBLE_PRECISION,MPI_MIN,MPI_COMM_WORLD,IERR)
	IF(INCREASE .NE. T1)IINC=0
	I=IINC; CALL MPI_ALLREDUCE(I,IINC,IONE,MPI_INTEGER,MPI_MAX,MPI_COMM_WORLD,IERR)
!
	T1=MAX_dT_COR; CALL MPI_ALLREDUCE(T1,MAX_dT_COR,IONE,MPI_DOUBLE_PRECISION,MPI_MAX,MPI_COMM_WORLD,IERR)
!
	IF(MYPE .EQ. 0)ALLOCATE(STRING(ND))
	CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	SCAT_DISP=SCAT_DISP*LEN(LOC_STRING(1))
	SCAT_SIZE=SCAT_SIZE*LEN(LOC_STRING(1))
	CALL MPI_GATHERV(LOC_STRING(DST:DEND),SCAT_SIZE(MYPE),MPI_CHARACTER,STRING,SCAT_SIZE,SCAT_DISP,
	1                            MPI_CHARACTER,IZERO,MPI_COMM_WORLD,IERR)
	DEALLOCATE(LOC_STRING,SCAT_DISP,SCAT_SIZE)
!
! Only processor 0 needs to write out the data file.
!
	IF(MYPE .GT. 0)RETURN
	CALL GET_LU(LU_SUM,'In create_correction_sum_mpi_v1')
	  CALL GEN_ASCI_OPEN(LU_SUM,'CORRECTION_SUM','UNKNOWN',' ',' ',IZERO,IOS)
	  WRITE(LU_SUM,'(A)')' '
	  WRITE(LU_SUM,'(A)')' Summary of changes at each depth '
	  WRITE(LU_SUM,'(A,I6)')' NT=',NT
	  WRITE(LU_SUM,'(A)')' '
	  WRITE(LU_SUM,'(3X,A,7(1X,A))')'Depth',' 100.0%','  10.0%','   1.0%',
	1        '   0.1%','  0.01%',' 0.001%','0.0001%'
!
	  DO J=1,ND
	    WRITE(LU_SUM,'(A)')TRIM(STRING(J))
	  END DO
	CLOSE(LU_SUM)
!
	DEALLOCATE(STRING)
	RETURN
	END
