	MODULE OLD_GRID_MODULE
	USE SET_KIND_MODULE
!
! Updated 09-Jan-2024 -- Added OLD_dED_ON_NA_dTAU and OLD_dlnT_dTAY
!
          REAL(KIND=LDP), ALLOCATABLE :: OLD_R(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_T(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_V(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_SIGMA(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_ED(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_POP_ATOM(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_POPION(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_MASS_DENSITY(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_CLUMP_FAC(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_dED_ON_NA_dTAU(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_dlnT_dTAU(:)
!
          REAL(KIND=LDP), ALLOCATABLE :: OLD_TAU(:)
	  REAL(KIND=LDP), ALLOCATABLE :: OLD_SF(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_ESEC(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_ROSS_MEAN(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_FLUX_MEAN(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_KAP_ROSS(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_KAP_FLUX(:)
          REAL(KIND=LDP), ALLOCATABLE :: OLD_KAP_ESEC(:)
!
	  REAL(KIND=LDP), ALLOCATABLE :: HYDRO_TAU(:)
	  REAL(KIND=LDP), ALLOCATABLE :: HYDRO_ERROR(:,:)
	  REAL(KIND=LDP), ALLOCATABLE :: HYDRO_ACTUAL_GAMMA(:,:)
	  REAL(KIND=LDP), ALLOCATABLE :: HYDRO_PREDICTED_GAMMA(:,:)
!
	  INTEGER, SAVE :: HYDRO_CNT=0
	  INTEGER OLD_ND
!
	END MODULE OLD_GRID_MODULE
