!
! Subroutine to store entie BA variation file on disk. The BA data in
! this version is passed via a data module. Unlike earlier routines,
! STEQ is NOT written out.
!
	SUBROUTINE READ_BA_DATA_MPI_V1(LU,NION,NUM_BNDS,COMPUTE_BA,FIXED_T,SUCCESSFUL_READ,DESC)
	USE SET_KIND_MODULE
	USE MOD_CMFGEN
	USE STEQ_DATA_MOD
	USE MOL_RXN_MOD
	IMPLICIT NONE
!
! Altered 29-Jul-2024 - Added ability to BA to be output to SCRATCH directory.
! Altered 16-Jul-2019 - Now reads in BA_T_EHB
! Altered 04-Oct-2016 - Added FIXED_T to call.
! Altered 12-Mar-2014 - COMPUTE_BA is nolonger changed by the routine. The value in CMFGEN
!                         is used to indicate whether the BA matric will be read in.
! Altered 07-Mar-2004 - BA no longer read in if COMPUTE_BA=.TRUE.
! Created 02-Apr-2001 - Created to handle SE data structure.
!                         See READBA for earlier corrections.
!
	INTEGER NION
	INTEGER NUM_BNDS
        INTEGER LU                    !Input unit for BA and STEQ
	LOGICAL COMPUTE_BA  		!Indicates whether BA is being computed.
	LOGICAL FIXED_T                 !Indicates whether T is to be held fixed.
	LOGICAL SUCCESSFUL_READ                  !Indicates whether BA/STEQ read successful
	CHARACTER DESC*(*)              !Used for filename
!
! Local Variables and external functions.
!
	INTEGER NUM_BNDS_RD,DST_RD,DEND_RD,NION_RD
	INTEGER ID
	INTEGER LUER,ERROR_LU,IOS
	EXTERNAL ERROR_LU
	LOGICAL FILE_OPEN
	LOGICAL COMPUTE_BA_RD
	INTEGER, PARAMETER :: IZERO=0
	CHARACTER(LEN=5) FILE_EXT
	CHARACTER(LEN=200) FILE_NAME
	CHARACTER(LEN=200), SAVE :: SCRATCH_DIR='GARBAGE'
!
	LUER=ERROR_LU()
	SUCCESSFUL_READ=.FALSE.
	IF(SCRATCH_DIR .EQ. 'GARBAGE')THEN
	  CALL GET_ENVIRONMENT_VARIABLE('SCRATCH_DIR',SCRATCH_DIR)
	  IF(SCRATCH_DIR .NE. ' '. AND. MYPE .EQ. 0)THEN
	    WRITE(LUER,'(/,1X,2A)')'Scratch directory is: ',TRIM(SCRATCH_DIR)
	    FLUSH(UNIT=LUER)
	  END IF
	END IF
!
! If we are still computing the BA matrix, there is no need to read it in.
!
	IF(COMPUTE_BA)THEN
	  RETURN
	END IF
	WRITE(FILE_EXT,'(I4.4)')MYPE; FILE_EXT='_'//FILE_EXT
	FILE_NAME=TRIM(SCRATCH_DIR)//TRIM(DESC)//TRIM(FILE_EXT)//'PNT'
	CALL GEN_ASCI_OPEN(LU,TRIM(FILE_NAME),'OLD',' ','READ',IZERO,IOS)
	IF(IOS .NE. 0)GOTO 300
	  READ(LU,*,ERR=400,IOSTAT=IOS)SUCCESSFUL_READ
	  IF(.NOT. SUCCESSFUL_READ)THEN
	    WRITE(LUER,*)'Previous store of '//TRIM(FILE_NAME),' was not completed succesfully'
	    CLOSE(UNIT=LU)
	    RETURN
	  END IF
	  READ(LU,*,ERR=400,IOSTAT=IOS)FIXED_T
	  READ(LU,*,ERR=400,IOSTAT=IOS)COMPUTE_BA_RD
	  READ(LU,*,ERR=400,IOSTAT=IOS)NION_RD
	  READ(LU,*,ERR=400,IOSTAT=IOS)NUM_BNDS_RD
	  READ(LU,*,ERR=400,IOSTAT=IOS)DST_RD
	  READ(LU,*,ERR=400,IOSTAT=IOS)DEND_RD
	  IF (INC_MOL) THEN
	     READ(LU,*,ERR=400,IOSTAT=IOS)N_MOL_LEVS
	  END IF
	CLOSE(UNIT=LU)
!
	IF(NION_RD .NE. NION .OR. NUM_BNDS_RD .NE. NUM_BNDS .OR. DST_RD .NE. DST .OR. DEND_RD .NE. DEND)THEN
	  WRITE(LUER,*)'Error : incompatible dimensions in BAREAD'
	  WRITE(LUER,*)'Skipping READ of BA and STEQ'
	  WRITE(LUER,*)'  Read vales:',NION_RD,NUM_BNDS_RD,DST_RD,DEND_RD
	  WRITE(LUER,*)'Actual vales:',NION,NUM_BNDS,DST,DEND
	  CLOSE(UNIT=LU)
          SUCCESSFUL_READ=.FALSE.
	  RETURN
	END IF
!
	FILE_NAME=TRIM(SCRATCH_DIR)//TRIM(DESC)//TRIM(FILE_EXT)
	OPEN(UNIT=LU,FORM='UNFORMATTED',FILE=FILE_NAME,IOSTAT=IOS,ERR=500,
	1             ACCESS='SEQUENTIAL',STATUS='OLD',ACTION='READ')
	  DO ID=1,NION
	    READ(LU,ERR=600,IOSTAT=IOS)SE(ID)%BA(:,:,:,DST:DEND)
	  END DO
	  READ(LU,ERR=605,IOSTAT=IOS)BA_ED
	  READ(LU,ERR=610,IOSTAT=IOS)BA_T
	  READ(LU,ERR=610,IOSTAT=IOS)BA_T_EHB
	  IF (INC_MOL) THEN
	     IF(.NOT. ALLOCATED(MTOT_BA)) ALLOCATE(MTOT_BA(N_MOL_LEVS,N_MOL_LEVS+2,DST:DEND))
	     READ(LU,ERR=615,IOSTAT=IOS)MTOT_BA
	  END IF
	CLOSE(UNIT=LU)
	RETURN
!
300	IF(MYPE .EQ. 0)THEN
	  WRITE(LUER,*)'Error opening '//TRIM(FILE_NAME)//' in READBA'
          WRITE(LUER,*)'IOSTAT=',IOS
	END IF
	SUCCESSFUL_READ=.FALSE.
	INQUIRE(UNIT=LU,OPENED=FILE_OPEN)
	IF(FILE_OPEN)CLOSE(UNIT=LU)
	RETURN
!
400	IF(MYPE .EQ. 0)THEN
	  WRITE(LUER,*)'Error reading from '//TRIM(FILE_NAME)//' in READBA'
          WRITE(LUER,*)'IOSTAT=',IOS
	END IF
	SUCCESSFUL_READ=.FALSE.
	INQUIRE(UNIT=LU,OPENED=FILE_OPEN)
	IF(FILE_OPEN)CLOSE(UNIT=LU)
	RETURN
!
500	IF(MYPE .EQ. 0)THEN
	  WRITE(LUER,*)'Error opening logical unit to recall :',TRIM(FILE_NAME)
          WRITE(LUER,*)'IOSTAT=',IOS
	END IF
	SUCCESSFUL_READ=.FALSE.
	INQUIRE(UNIT=LU,OPENED=FILE_OPEN)
	IF(FILE_OPEN)CLOSE(UNIT=LU)
	RETURN
!
600	IF(MYPE .EQ. 0)THEN
	  WRITE(LUER,*)'Error on reading SE(ID)%BA in READ_BA_DATA_V2: ',TRIM(FILE_NAME)
          WRITE(LUER,*)'IOSTAT=',IOS
	END IF
	SUCCESSFUL_READ=.FALSE.
	INQUIRE(UNIT=LU,OPENED=FILE_OPEN)
	IF(FILE_OPEN)CLOSE(UNIT=LU)
	RETURN
!
605	IF(MYPE .EQ. 0)THEN
	  WRITE(LUER,*)'Error on reading BA_ED in READ_BA_DATA_V2: ',TRIM(FILE_NAME)
          WRITE(LUER,*)'IOSTAT=',IOS
	END IF
	SUCCESSFUL_READ=.FALSE.
	INQUIRE(UNIT=LU,OPENED=FILE_OPEN)
	IF(FILE_OPEN)CLOSE(UNIT=LU)
	RETURN
!
610	IF(MYPE .EQ. 0)THEN
	  WRITE(LUER,*)'Error on reading BA_T in READ_BA_DATA_V2: ',TRIM(FILE_NAME)
          WRITE(LUER,*)'IOSTAT=',IOS
	END IF
	SUCCESSFUL_READ=.FALSE.
	INQUIRE(UNIT=LU,OPENED=FILE_OPEN)
	IF(FILE_OPEN)CLOSE(UNIT=LU)
	RETURN
!	
 615	IF(MYPE .EQ. 0)THEN
	  WRITE(LUER,*)'Error on reading MTOT_BA in READ_BA_DATA_V2: ',TRIM(FILE_NAME)
          WRITE(LUER,*)'IOSTAT=',IOS
	END IF
	SUCCESSFUL_READ=.FALSE.
	INQUIRE(UNIT=LU,OPENED=FILE_OPEN)
	IF(FILE_OPEN)CLOSE(UNIT=LU)
	RETURN	
!
	RETURN
	END
