	MODULE MOD_SAVE_STEQ_ION
	USE SET_KIND_MODULE
	REAL(KIND=LDP), ALLOCATABLE, SAVE :: STEQ_ION_STORE(:,:)
	END MODULE MOD_SAVE_STEQ_ION
!
	SUBROUTINE SAVE_STEQ_ION(STEQ_ION,DEPTH_INDX,NION,DST,DEND)
	USE SET_KIND_MODULE
	USE MOD_SAVE_STEQ_ION
	IMPLICIT NONE
!
	REAL(KIND=LDP) STEQ_ION(NION)
	INTEGER DEPTH_INDX
	INTEGER NION
	INTEGER DST,DEND
!
	IF(.NOT. ALLOCATED(STEQ_ION_STORE))THEN
	  ALLOCATE(STEQ_ION_STORE(NION,DST:DEND))
	END IF
!
	STEQ_ION_STORE(:,DEPTH_INDX)=STEQ_ION(:)
!
	RETURN 
	END
!
	SUBROUTINE WRITE_STEQ_ION(NION,DST,DEND,ND)
	USE SET_KIND_MODULE
	USE MOD_SAVE_STEQ_ION
	IMPLICIT NONE
	INTEGER NION,DST,DEND,ND
	LOGICAL, PARAMETER :: L_TRUE=.TRUE.
!
	CALL WR2D_GATH_MPI_V1(STEQ_ION_STORE,NION,DST,DEND,ND,'STEQ_ION','$',L_TRUE,16)
	RETURN
	END SUBROUTINE WRITE_STEQ_ION
