!
! Declares arrays required for the angular quadrature weights, and
! computes their vaule. Routine can be called more than once, although
! the size of the declared arrays must not change.
!
	SUBROUTINE SET_ANG_QW_MPI(R,P,NC,ND,NP,TRAPFORJ)
	USE SET_KIND_MODULE
	USE FG_J_CMF_MOD_MPI_V1
	IMPLICIT NONE
!
! Created 11-Aug-2024
!
	INTEGER NC,ND,NP
	REAL(KIND=LDP) R(ND)
	REAL(KIND=LDP) P(NP)
	LOGICAL TRAPFORJ
!
! External function calls.
!
	EXTERNAL JWEIGHT_V2,HWEIGHT_V2,KWEIGHT_V2,NWEIGHT_V2
	EXTERNAL JTRPWGT_V2,HTRPWGT_V2,KTRPWGT_V2,NTRPWGT_V2
	EXTERNAL ERROR_LU
	INTEGER ERROR_LU
!
	REAL(KIND=LDP), ALLOCATABLE :: AQW(:,:)
!
	INTEGER LU_ER
	INTEGER LS
	INTEGER IOS
	INTEGER IPROC
	LOGICAL MID
	LOGICAL AQW_ALLOCATED
!
	INTEGER GET_LS,I
	GET_LS(MYPE,NTHREAD,I)=MOD(I,2)*(MYPE+(I-1)*NTHREAD+1)+MOD(I+1,2)*(I*NTHREAD-MYPE)
!
	AQW_ALLOCATED=.FALSE.
!
! Allocate wory arrays.
!
	ALLOCATE(AQW(ND,NP),STAT=IOS)
!
	DO IPROC=1,NUM_RAYS_PER_THREAD
	  IF(IPROC .GT. 1)THEN
	  ELSE IF(TRAPFORJ)THEN
	    CALL NORDANGQW_V2(AQW,R,P,NC,ND,NP,JTRPWGT_V2)
	  ELSE
	    CALL NORDANGQW_V2(AQW,R,P,NC,ND,NP,JWEIGHT_V2)
	  END IF
	  LS=GET_LS(MYPE,NTHREAD,IPROC)
	  IF(LS .GT. NP)EXIT
	  IF( ALLOCATED(RAY(LS)%JQW) )AQW_ALLOCATED=.TRUE.
	  IF(.NOT. AQW_ALLOCATED)ALLOCATE(RAY(LS)%JQW(ND))
	  RAY(LS)%JQW(1:ND)=AQW(1:ND,LS)
	END DO
!
	DO IPROC=1,NUM_RAYS_PER_THREAD
	  IF(IPROC .GT. 1)THEN
	  ELSE IF(TRAPFORJ)THEN
	    CALL NORDANGQW_V2(AQW,R,P,NC,ND,NP,HTRPWGT_V2)
	  ELSE
	    CALL NORDANGQW_V2(AQW,R,P,NC,ND,NP,HWEIGHT_V2)
	  END IF
	  LS=GET_LS(MYPE,NTHREAD,IPROC)
	  IF(LS .GT. NP)EXIT
	  IF(.NOT. AQW_ALLOCATED)ALLOCATE(RAY(LS)%HQW(ND))
	  RAY(LS)%HQW(1:ND)=AQW(1:ND,LS)
	END DO
!
	DO IPROC=1,NUM_RAYS_PER_THREAD
	  IF(IPROC .GT. 1)THEN
	  ELSE IF(TRAPFORJ)THEN
	    CALL NORDANGQW_V2(AQW,R,P,NC,ND,NP,KTRPWGT_V2)
	  ELSE
	    CALL NORDANGQW_V2(AQW,R,P,NC,ND,NP,KWEIGHT_V2)
	  END IF
	  LS=GET_LS(MYPE,NTHREAD,IPROC)
	  IF(LS .GT. NP)EXIT
	  IF(.NOT. AQW_ALLOCATED)ALLOCATE(RAY(LS)%KQW(ND))
	  RAY(LS)%KQW(1:ND)=AQW(1:ND,LS)
	END DO
!
	DO IPROC=1,NUM_RAYS_PER_THREAD
	  IF(IPROC .GT. 1)THEN
	  ELSE IF(TRAPFORJ)THEN
	    CALL NORDANGQW_V2(AQW,R,P,NC,ND,NP,NTRPWGT_V2)
	  ELSE
	    CALL NORDANGQW_V2(AQW,R,P,NC,ND,NP,NWEIGHT_V2)
	  END IF
	  LS=GET_LS(MYPE,NTHREAD,IPROC)
	  IF(LS .GT. NP)EXIT
	  IF(.NOT. AQW_ALLOCATED)ALLOCATE(RAY(LS)%NQW(ND))
	  RAY(LS)%NQW(1:ND)=AQW(1:ND,LS)
	END DO
!
!
	DO IPROC=1,NUM_RAYS_PER_THREAD
	  MID=.TRUE.
	  IF(IPROC .GT. 1)THEN
	  ELSE IF(TRAPFORJ)THEN
	    CALL GENANGQW_V2(AQW,R,P,NC,ND,NP,HTRPWGT_V2,MID)
	  ELSE
	    CALL GENANGQW_V2(AQW,R,P,NC,ND,NP,HWEIGHT_V2,MID)
	  END IF
	  LS=GET_LS(MYPE,NTHREAD,IPROC)
	  IF(LS .GT. NP)EXIT
	  IF(.NOT. AQW_ALLOCATED)ALLOCATE(RAY(LS)%HMIDQW(ND))
	  RAY(LS)%HMIDQW(1:ND)=AQW(1:ND,LS)
	END DO
!
	DO IPROC=1,NUM_RAYS_PER_THREAD
	  MID=.TRUE.
	  IF(IPROC .GT. 1)THEN
	  ELSE IF(TRAPFORJ)THEN
	    CALL GENANGQW_V2(AQW,R,P,NC,ND,NP,HTRPWGT_V2,MID)
	  ELSE
	    CALL GENANGQW_V2(AQW,R,P,NC,ND,NP,HWEIGHT_V2,MID)
	  END IF
	  LS=GET_LS(MYPE,NTHREAD,IPROC)
	  IF(LS .GT. NP)EXIT
	  IF(.NOT. AQW_ALLOCATED)ALLOCATE(RAY(LS)%NMIDQW(ND))
	  RAY(LS)%NMIDQW(1:ND)=AQW(1:ND,LS)
	END DO
!
	DEALLOCATE(AQW)
!
	RETURN
	END SUBROUTINE SET_ANG_QW_MPI
