!
! Routine to write a 2D Matrix out as a "MATRIX" . A maximum of ten
! numbers are written across the page.
!
! Altered 13-Dec-1989 - Implicit none installed. I index written out.
!
	SUBROUTINE WR_ASCI_STEQ_MPI_V1(NION,DST,DEND,ND,MES,LU)
	USE SET_KIND_MODULE
	USE MPI
	USE STEQ_DATA_MOD
	IMPLICIT NONE
	INTEGER ND,NION,LU
	INTEGER DST,DEND
	CHARACTER*(*) MES
!
	INTEGER MS,MF,ML,I,J,ID
	INTEGER NX,IERR
!
!	include 'mpif.h'
!
	TYPE LOCAL_SE
	  REAL(KIND=LDP), ALLOCATABLE :: ROOT_STEQ(:,:)
	END TYPE LOCAL_SE
	TYPE (LOCAL_SE), SAVE :: RT(500)
	LOGICAL, SAVE :: FIRST=.TRUE.
!
	IF(ALLOCATED(RT(1)%ROOT_STEQ))THEN
	ELSE IF(MYPE .EQ. 0)THEN
	  DO ID=1,NION
	    NX=1
	    IF(SE(ID)%XzV_PRES)NX=SE(ID)%N_SE 
	    ALLOCATE(RT(ID)%ROOT_STEQ(NX,ND))
	    RT(ID)%ROOT_STEQ=0.0_LDP
	  END DO
	ELSE 
!
! ROOT_STEQ is only accessed my the root process.
!
	  NX=1
	  DO ID=1,NION
	    ALLOCATE(RT(ID)%ROOT_STEQ(NX,NX))
	  END DO
	END IF
!
	IF(FIRST)THEN
	  CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
	  FIRST=.FALSE.
	END IF
!
	DO ID=1,NION
	  IF(SE(ID)%XzV_PRES)THEN
	    NX=SE(ID)%N_SE
	    CALL GATHER_MAT_TO_ROOT_MPI_V1(SE(ID)%STEQ,DST,DEND,RT(ID)%ROOT_STEQ,NX,ND)
	  END IF
	END DO
	IF(MYPE .NE. 0)RETURN
!
	WRITE(LU,'(/,1X,A)')MES
	MS=1
	NX=10
	DO ML=0,ND-1,NX
	  MF=ML+NX
	  IF(MF .GT. ND)MF=ND
	  WRITE(LU,'(/)')
	  DO ID=1,NION
	    IF(SE(ID)%XzV_PRES)THEN
	      DO I=1,SE(ID)%N_SE
	        WRITE(LU,110)MS,ID,I,' * ',(RT(ID)%ROOT_STEQ(I,J),J=MS,MF)
	      END DO
	    END IF
	  END DO
	  MS=MS+NX
	END DO
	FLUSH(UNIT=LU)
!
110	FORMAT(1X,I4,2X,I2,2X,I4,A3,10ES12.4)
	RETURN
	END
