!
! Subroutine to output ETA and CHI in mpi distribution of CMFGEN.
! MYPE=0 must be used for output.
!
	SUBROUTINE WRITE_ETA_CHI(R,V,LANG_COORD,ETA,CHI,FREQ,NCF,ND)
	USE SET_KIND_MODULE
	USE EDDFAC_REC_DEFS_MOD
	IMPLICIT NONE
!
	INTEGER NCF,ND
	REAL(KIND=LDP) R(ND)
	REAL(KIND=LDP) V(ND)
	REAL(KIND=LDP) LANG_COORD(ND)
	REAL(KIND=LDP) ETA(ND)
	REAL(KIND=LDP) CHI(ND)
	REAL(KIND=LDP) FREQ
!
	LOGICAL, PARAMETER :: L_TRUE=.TRUE.
	LOGICAL, PARAMETER :: L_FALSE=.FALSE.
	LOGICAL,      SAVE :: FIRST=.TRUE.
!
	INTEGER, SAVE :: LU_CHI
	INTEGER, SAVE :: LU_ETA
	INTEGER, SAVE :: OUT_REC
	INTEGER, SAVE :: FINAL_REC
	LOGICAL COMPUTE_DATA           	!Must be read/write
	INTEGER K
!
! NB: The OPEN_RW_EDDFACTOR routine opens ETA_DATA for read/write output for MYPE=0
!        For other processes it only opened for reading. In practice,  these other
!        processes will not access ETA_DATA.
!
! COMPUTE_DATA is updated in OPEN_RW_EDDFACTOR so it is always consistent with MYPE=0.
!
	COMPUTE_DATA=.TRUE.
	IF(FIRST)THEN
          CALL GET_LU(LU_ETA,'ETA_DATA write')
          CALL OPEN_RW_EDDFACTOR(R,V,LANG_COORD,ND,
	1              R,V,LANG_COORD,ND,
	1              K,L_TRUE,COMPUTE_DATA,L_FALSE,'ETA_DATA',LU_ETA)
          OUT_REC=INITIAL_ACCESS_REC
          IF(MYPE .EQ. 0)WRITE(LU_ETA,REC=EDD_CONT_REC)OUT_REC,NCF,ND
!
          CALL GET_LU(LU_CHI,'CHI_DATA write')
          CALL OPEN_RW_EDDFACTOR(R,V,LANG_COORD,ND,
	1              R,V,LANG_COORD,ND,
	1              K,L_TRUE,COMPUTE_DATA,L_FALSE,'CHI_DATA',LU_CHI)
          IF(MYPE .EQ. 0)WRITE(LU_CHI,REC=EDD_CONT_REC)OUT_REC,NCF,ND
	END IF
	FIRST=.FALSE.
!
	IF(MYPE .EQ. 0)THEN
          WRITE(LU_ETA,REC=OUT_REC)ETA,FREQ
          WRITE(LU_CHI,REC=OUT_REC)CHI,FREQ
	END IF
	OUT_REC=OUT_REC+1
	IF(OUT_REC .EQ. INITIAL_ACCESS_REC+NCF)THEN
	   CLOSE(LU_ETA); CLOSE(LU_CHI)
	END IF
!
	RETURN
	END
