	MODULE MOD_PHOT_THREAD_INFO
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER NU_THRD
	REAL(KIND=LDP), ALLOCATABLE ::  COMP_FREQ(:)
	LOGICAL COMPUTE_NEW_CROSS_SECTIONS
	SAVE
!
	END MODULE MOD_PHOT_THREAD_INFO
!
	SUBROUTINE INIT_PHOT_CALL(CONT_FREQ)
	USE SET_KIND_MODULE
	USE MOD_PHOT_THREAD_INFO
	IMPLICIT NONE
!
	REAL(KIND=LDP) CONT_FREQ
!
	IF(.NOT. ALLOCATED(COMP_FREQ))THEN
	  ALLOCATE(COMP_FREQ(NTHREAD))
	END IF
!	
	NU_THRD=0
	COMPUTE_NEW_CROSS_SECTIONS=.TRUE.
	IF(COMP_FREQ(MYPE) .EQ. CONT_FREQ)THEN
	  NU_THRD=MYPE
	  COMPUTE_NEW_CROSS_SECTIONS=.FALSE.
	END IF
!
	RETURN
	END
!
	SUBROUTINE FINAL_PHOT_CALL
	USE SET_KIND_MODULE
	USE MOD_PHOT_THREAD_INFO
	IMPLICIT NONE
!
	COMPUTE_NEW_CROSS_SECTIONS=.FALSE.
!
	RETURN
	END
!
	SUBROUTINE GET_PHOT_CROSS_SECTIONS_V1(
	1              FREQ,NU,NU_EVAL_CONT,CUR_ML,NCF,
	1              ID,PHOT,GS_EDGE,NLEVS,PHOT_ID,SET_TO_EDGE)
	USE SET_KIND_MODULE
	USE MOD_PHOT_THREAD_INFO
	USE PHOT_DATA_MOD
	USE MPI
	IMPLICIT NONE
!
! Variable not specicific to any species.
!
	INTEGER NCF
	INTEGER CUR_ML
	REAL(KIND=LDP) FREQ
	REAL(KIND=LDP) NU(NCF)
	REAL(KIND=LDP) NU_EVAL_CONT(NCF)
!
	INTEGER ID
	INTEGER NLEVS
	INTEGER PHOT_ID
	REAL(KIND=LDP) PHOT(NLEVS)
	REAL(KIND=LDP) GS_EDGE(NLEVS)
	LOGICAL SET_TO_EDGE
!
! Local variables.
!
	INTEGER I,K,IERR
!
	IF(FREQ .NE. COMP_FREQ(NU_THRD))THEN
	  WRITE(6,*)'Error -- issue computine photoiozation cross-sections'
	  WRITE(6,*)'An inconsistency has arisen in SET_PHOT_CALL'
	  WRITE(6,*)'ML,PCNT_FREQ=',CUR_ML,FREQ
	  STOP
	END IF
!
	IF(COMPUTE_NEW_CROSS_SECTIONS)THEN
!
! Each processor computes the cross-section for 1 frequency.
!
	  WRITE(6,*)'New phot',MYPE,ID,FREQ,NLEVS; FLUSH(UNIT=6)
	  K=CUR_ML+MYPE
	  IF(K .LE. NCF)THEN
	    FREQ=NU_EVAL_CONT(K)
	    CALL SUB_PHOT_GEN_MPI_V1(ID,PHOT,FREQ,GS_EDGE,NLEVS,PHOT_ID,SET_TO_EDGE)
	  END IF
!
! Make sure all processes know what frequencies had photoionization cross-sections computed.
!
	  DO I=0,NTHREAD-1
	    IF(CUR_ML+I .LE. NCF)THEN
	      COMP_FREQ(I)=NU_EVAL_CONT(CUR_ML+I)
	    END IF
	  END DO
	  WRITE(6,*)'Done new phot',MYPE,ID,FREQ,NLEVS; FLUSH(UNIT=6)
	END IF
!
! Set the photoionization cross-sections on all nodes for the current frequency.
!
	 WRITE(6,*)'Doing broadcast',MYPE,ID,FREQ,NLEVS; FLUSH(UNIT=6)
	IF(MYPE .EQ. NU_THRD)THEN
	  PHOT(1:NLEVS)=PD(ID)%LST_CROSS(1:NLEVS,PHOT_ID)
	END IF
	CALL MPI_BCAST(PHOT,NLEVS,MPI_DOUBLE_PRECISION,NU_THRD,MPI_COMM_WORLD,IERR)
	WRITE(6,*)'Done broadcast',MYPE,ID,FREQ,NLEVS; FLUSH(UNIT=6)
!
	RETURN
	END
