!
! This routine can be compiled instead of set_phot_cross-sections.f. Make
! sure other versions are not beeing compiled, and have been deleted from
! libsubs.a
!
        MODULE MOD_PHOT_THREAD_INFO
        USE SET_KIND_MODULE
        IMPLICIT NONE
        REAL(KIND=LDP), ALLOCATABLE ::  COMP_FREQ(:)
	REAL(KIND=LDP), POINTER :: PHOT_DATA(:,:)
	INTEGER, POINTER :: PHOT_DATA_LOC(:,:,:)
	INTEGER, POINTER :: PHOT_DATA_LEV(:,:,:)
!
	INTEGER PHOT_DATA_WIN
	INTEGER PHOT_DATA_LOC_WIN
	INTEGER PHOT_DATA_LEV_WIN
	INTEGER MAX_N_PHOT
!
	SAVE
	END MODULE  MOD_PHOT_THREAD_INFO
!
! Subroutine to compute the photoionization cross-sections for all species.
! In this routine, each processor computes a separate photoionization
! cross-section. The data are then shared to other processors using
! shared memory.
!
	SUBROUTINE SET_PHOT_ACCESS_LOC()
	USE SET_KIND_MODULE
	USE MOD_PHOT_THREAD_INFO
	USE MOD_CMFGEN
	USE ALLOCATE_SHARED_MEM
	USE MPI
	USE ISO_C_BINDING, ONLY: C_PTR, C_F_POINTER
	IMPLICIT NONE
!
	TYPE(C_PTR) BASEPTR
	REAL(KIND=LDP) X
	INTEGER I,ID,CNT,NEEDED_SIZE,IER
	INTEGER DIM_ONE_SIZE, ARRAY_SIZE, VAR_SIZE
	INTEGER, PARAMETER :: IZERO=0
	LOGICAL, PARAMETER :: L_TRUE=.TRUE.
	LOGICAL, PARAMETER :: L_FALSE=.FALSE.
!
	CNT=1; MAX_N_PHOT=0
	DO ID=1,NUM_IONS
	  MAX_N_PHOT=MAX(MAX_N_PHOT,ATM(ID)%N_XzV_PHOT)
	  IF(ATM(ID)%XzV_PRES)THEN
	    CNT=CNT+ATM(ID)%NXzV_F*ATM(ID)%N_XzV_PHOT
	  END IF
	END DO
	DIM_ONE_SIZE=CNT-1
!
	VAR_SIZE=SIZEOF(X)
	ARRAY_SIZE=DIM_ONE_SIZE*NTHREAD
	CALL ALLOCATE_MPI_MEM(IZERO,ARRAY_SIZE,VAR_SIZE,BASEPTR,MPI_COMM_WORLD,PHOT_DATA_WIN)
	CALL C_F_POINTER(BASEPTR,PHOT_DATA,[DIM_ONE_SIZE,NTHREAD]) !,[1,0])
! 
	VAR_SIZE=SIZEOF(ID)
	ARRAY_SIZE=NUM_IONS*MAX_N_PHOT*NTHREAD
	CALL ALLOCATE_MPI_MEM(IZERO,ARRAY_SIZE,VAR_SIZE,BASEPTR,MPI_COMM_WORLD,PHOT_DATA_LOC_WIN)
	CALL C_F_POINTER(BASEPTR,PHOT_DATA_LOC,[NUM_IONS,MAX_N_PHOT,NTHREAD]) !,[1,1,0])
! 
	CALL ALLOCATE_MPI_MEM(IZERO,ARRAY_SIZE,VAR_SIZE,BASEPTR,MPI_COMM_WORLD,PHOT_DATA_LEV_WIN)
	CALL C_F_POINTER(BASEPTR,PHOT_DATA_LEV,[NUM_IONS,MAX_N_PHOT,NTHREAD]) !,[1,1,0])
! 
	IF(MYPE .EQ. 0)THEN
!
	  WRITE(6,*)' '
	  WRITE(6,*)' Using shared memory version to compute photoionization cross-sections.'
	  WRITE(6,*)' Each processor computes a phot. cross-sections for a different frequency.'
	  WRITE(6,*)' These are share using shared memory.'
	  WRITE(6,*)' Called file is set_phot_sections_shared_v1.f'
	  WRITE(6,*)' '
	  WRITE(6,*)'Created shared memory in SET_ACCESS_PHOT_LOC'
	  WRITE(6,*)' Expected PHOT_DATA size: ',DIM_ONE_SIZE,NTHREAD
	  WRITE(6,*)'   Actual PHOT_DATA size: ',SHAPE(PHOT_DATA)
	  WRITE(6,*)'  PHOT_DATA lower bounds: ',LBOUND(PHOT_DATA)
	  WRITE(6,*)'  PHOT_DATA upper bounds: ',UBOUND(PHOT_DATA)
!
	  WRITE(6,*)' '
	  WRITE(6,*)'Expected PHOT_DATA_LOC size: ',NUM_IONS,MAX_N_PHOT,NTHREAD
	  WRITE(6,*)'  Actual PHOT_DATA_LOC size: ',SHAPE(PHOT_DATA_LOC)
	  WRITE(6,*)' PHOT_DATA_LOC lower bounds: ',LBOUND(PHOT_DATA)
	  WRITE(6,*)' PHOT_DATA_LOC upper bounds: ',UBOUND(PHOT_DATA)
	  WRITE(6,*)' '
!
	  WRITE(6,*)'Expected PHOT_DATA_LEV size: ',NUM_IONS,MAX_N_PHOT,NTHREAD
	  WRITE(6,*)'  Actual PHOT_DATA_LEV size: ',SHAPE(PHOT_DATA_LEV)
	  WRITE(6,*)' PHOT_DATA_LEV lower bounds: ',LBOUND(PHOT_DATA)
	  WRITE(6,*)' PHOT_DATA_LEV upper bounds: ',UBOUND(PHOT_DATA)
	  FLUSH(UNIT=6)
	END IF
!
	RETURN
	END
!
! Subroutine to compute the photoionization cross-sections for all species.
!
	SUBROUTINE SET_PHOT_CROSS_SECTIONS_V1(FREQ,NU,NU_EVAL_CONT,CUR_ML,NCF)
	USE SET_KIND_MODULE
	USE MOD_PHOT_THREAD_INFO
	USE MOD_CMFGEN
	USE MPI
	IMPLICIT NONE
!
	INTEGER NCF
	INTEGER CUR_ML
	REAL(KIND=LDP) FREQ
	REAL(KIND=LDP) NU(NCF)
	REAL(KIND=LDP) NU_EVAL_CONT(NCF)
!
	REAL(KIND=LDP), SAVE, ALLOCATABLE :: ALPHA_VEC(:)
	LOGICAL, SAVE :: FIRST=.TRUE.
!
	REAL(KIND=LDP) LOC_FREQ
	INTEGER ID
	INTEGER PHOT_ID		!Photoionization ID (path)
!
	INTEGER I,K,ML,CNT,KST,IER
	LOGICAL, PARAMETER :: L_TRUE=.TRUE.
	LOGICAL, PARAMETER :: L_FALSE=.FALSE.
!
	IF(FIRST)THEN
	  ALLOCATE(COMP_FREQ(0:NTHREAD-1))
	  COMP_FREQ=0.0_LDP; K=0
	  DO ID=1,NUM_IONS
	    IF(ATM(ID)%XzV_PRES)K=MAX(K,ATM(ID)%NXZV_F)
	  END DO
	  ALLOCATE(ALPHA_VEC(K))
	  CALL SET_PHOT_ACCESS_LOC()
	  FIRST = .FALSE.
	  IF(MYPE .EQ. 0)WRITE(6,*)'Allocated COMP_FREQ,ALPHA_VEC in SET_PHOT_CROSS_SECTIONS_V1 (shared)'
	  FLUSH(UNIT=6)
	END IF
!
! Check if cross-section has already been computed.
!
	IF(FREQ .NE. 0.0_LDP)THEN
	  DO K=0,NTHREAD-1
	    IF(FREQ .EQ. COMP_FREQ(K))RETURN
	  END DO
	END IF
!
! Compute the photoionization cross-sections for all levels.
!
	IF(FREQ .NE. 0)THEN
!
	  COMP_FREQ=0.0_LDP
	  COMP_FREQ(0)=NU_EVAL_CONT(CUR_ML)
	  ML=CUR_ML+1
	  DO K=1,NTHREAD-1
	    DO I=ML,NCF
	      IF(NU_EVAL_CONT(I) .NE. COMP_FREQ(K-1))THEN
	        COMP_FREQ(K)=NU_EVAL_CONT(I)
	        ML=I+1
	        EXIT
	      END IF
	    END DO
	  END DO
!
	  CNT=1
          LOC_FREQ=COMP_FREQ(MYPE)
	  IF(LOC_FREQ .NE. 0.0_LDP)THEN
	    DO ID=1,NUM_IONS
	      IF(ATM(ID)%XzV_PRES)THEN
	        DO I=1,ATM(ID)%N_XzV_PHOT
	          PHOT_ID=I
	          CALL SUB_PHOT_GEN_MPI_V2(ID,ALPHA_VEC,LOC_FREQ,ATM(ID)%EDGEXZV_F,ATM(ID)%NXzV_F,PHOT_ID,L_FALSE)
	          KST=ATM(ID)%NXzV_F+1
	          DO K=1,ATM(ID)%NXzV_F
	            IF(ALPHA_VEC(K) .NE. 0)THEN
	              KST=K
	              EXIT
	            END IF
	          END DO
	          IF(KST .LE.  ATM(ID)%NXzV_F)PHOT_DATA_LOC(ID,PHOT_ID,MYPE+1)=CNT
	          PHOT_DATA_LEV(ID,PHOT_ID,MYPE+1)=KST 
	          DO K=KST,ATM(ID)%NXzV_F
	            PHOT_DATA(CNT,MYPE+1)=ALPHA_VEC(K)
	            CNT=CNT+1
	          END DO
	        END DO
	      END IF
	    END DO
	  END IF
	  CALL MPI_WIN_FENCE(0,PHOT_DATA_WIN,IER)
	  CALL MPI_WIN_FENCE(0,PHOT_DATA_LOC_WIN,IER)
	  CALL MPI_WIN_FENCE(0,PHOT_DATA_LEV_WIN,IER)
! 
	ELSE
!
! Compute the photoionization cross-sections for all levels at their edge frequencies.
! Only done for PHOT_ID .EQ. 1 at present.
!
	  DO ID=1,NUM_IONS
	    IF(ATM(ID)%XzV_PRES)THEN
	      DO I=1,ATM(ID)%N_XzV_PHOT
	        PHOT_ID=I
	        IF(FIRST .AND. PHOT_ID .EQ. 1)THEN
	          CALL SUB_PHOT_GEN_MPI_V2(ID,ALPHA_VEC,FREQ,ATM(ID)%EDGEXZV_F,ATM(ID)%NXzV_F,PHOT_ID,L_TRUE)
	        END IF
	      END DO
	    END IF
	  END DO
	END IF
	FLUSH(UNIT=6)
!
	RETURN
	END
!
	SUBROUTINE GET_PHOT_CROSS_SECTIONS_V1(PHOT,ID,PHOT_ID,NLEVS,FREQ,ADD_EDGE)
	USE SET_KIND_MODULE
	USE PHOT_DATA_MOD
	USE MOD_PHOT_THREAD_INFO
	USE MPI
	IMPLICIT NONE
!
	INTEGER ID
	INTEGER PHOT_ID
	INTEGER NLEVS
	REAL(KIND=LDP) PHOT(NLEVS)
	REAL(KIND=LDP) FREQ
	LOGICAL ADD_EDGE
!
	REAL(KIND=LDP) T1
	INTEGER I,K
	INTEGER L(2)
	INTEGER IERR
	INTEGER NU_THRD
	INTEGER ST_LOC,END_LOC,LEV_ST
!	
	NU_THRD=-2
	DO K=0,NTHREAD-1
	  IF(COMP_FREQ(K) .EQ. FREQ)THEN
	    NU_THRD=K
	    EXIT
	  END IF
	END DO
	IF(NU_THRD .LT. -1)THEN
	  WRITE(6,*)'Error -- photoionization cross-sections have not been computed' 
	  WRITE(6,*)MYPE,FREQ
	  WRITE(6,*)COMP_FREQ
	  FLUSH(UNIT=6)
	  STOP
	END IF
!
! Set the photoionization cross-sections on all nodes for the current
! frequency.
!
	LEV_ST=PHOT_DATA_LEV(ID,PHOT_ID,NU_THRD+1)
	ST_LOC=PHOT_DATA_LOC(ID,PHOT_ID,NU_THRD+1)
	END_LOC=ST_LOC+(NLEVS-LEV_ST)
	PHOT(1:LEV_ST-1)=0.0_LDP
	PHOT(LEV_ST:NLEVS)=PHOT_DATA(ST_LOC:END_LOC,NU_THRD+1)
!
	IF(ADD_EDGE .AND. PHOT_ID .EQ. 1)THEN
	  DO I=1,NLEVS
	    T1=PD(ID)%EDGE_FREQ(I,PHOT_ID)
	    IF(FREQ .GE. 0.5_LDP*T1 .AND. FREQ .LT. T1)THEN
	      PHOT(I)=PD(ID)%EDGE_CROSS(I,PHOT_ID)
	    END IF
	  END DO
	 END IF
!
	RETURN
	END
!
	SUBROUTINE GET_EDGE_CROSS_SECTIONS_V1(PHOT,ID,PHOT_ID,NLEVS)
	USE SET_KIND_MODULE
	USE PHOT_DATA_MOD
	USE MOD_PHOT_THREAD_INFO
!
	INTEGER ID
	INTEGER PHOT_ID
	INTEGER NLEVS
	REAL(KIND=LDP) PHOT(NLEVS)
!
	PHOT(1:NLEVS)=PD(ID)%EDGE_CROSS(1:NLEVS,PHOT_ID)
!
	RETURN
	END
