	SUBROUTINE ALL_GATHERV_VEC_MPI_V1(VECTOR,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER ND
	REAL(KIND=LDP) VECTOR(ND)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER K
	INTEGER IERR
	INTEGER NUM_DEPTHS_PER_THREAD
!
	include 'mpif.h'
!
	NUM_DEPTHS_PER_THREAD=(ND-1)/NTHREAD+1
	IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	  ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	  ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	END IF
!
! Work out send size and displacements if just sending a vector of length ND.
!
	DO K=0,NTHREAD-1
	  SCAT_DISP(K)=K*NUM_DEPTHS_PER_THREAD
	  SCAT_SIZE(K)=NUM_DEPTHS_PER_THREAD
	  IF(SCAT_DISP(K)+SCAT_SIZE(K) .GT. ND)SCAT_SIZE(K)=ND-SCAT_DISP(K)
	END DO
	CALL MPI_ALLGATHERV(MPI_IN_PLACE,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1               VECTOR,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,MPI_COMM_WORLD,IERR)
!
	RETURN
	END
