	SUBROUTINE COMP_VAR_JREC_MPI_V1(JREC,dJRECdT,JPHOT,
	1                  JREC_CR,dJREC_CRdT,JPHOT_CR,BPHOT_CR,
	1                  RJ,EMHNUKT,T,NU,FQW,TWOHCSQ,HDKT,
	1                  DST,DEND,ND,COMP_NEW_CONT)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
! Altered 14-Jul-2019 : Added dJREC_CRdT to call and hanged to V2
!
	INTEGER ND
	INTEGER DST,DEND
!
	REAL(KIND=LDP) JREC(DST:DEND)
	REAL(KIND=LDP) dJRECdT(DST:DEND)
	REAL(KIND=LDP) JPHOT(DST:DEND)
	REAL(KIND=LDP) JREC_CR(DST:DEND)
	REAL(KIND=LDP) dJREC_CRdT(DST:DEND)
	REAL(KIND=LDP) JPHOT_CR(DST:DEND)
	REAL(KIND=LDP) BPHOT_CR(DST:DEND)
!
	REAL(KIND=LDP) RJ(ND)
	REAL(KIND=LDP) EMHNUKT(ND)
	REAL(KIND=LDP) T(ND)
	REAL(KIND=LDP) NU
	REAL(KIND=LDP) FQW
	REAL(KIND=LDP) HDKT,TWOHCSQ
	LOGICAL COMP_NEW_CONT
C
	REAL(KIND=LDP) T1,T2
	INTEGER I
C
	IF(COMP_NEW_CONT)THEN
	  JREC(:)=0.0_LDP
	  dJRECdT(:)=0.0_LDP
	  JPHOT(:)=0.0_LDP
	  JREC_CR(:)=0.0_LDP
	  dJREC_CRdT(:)=0.0_LDP
	  JPHOT_CR(:)=0.0_LDP
	  BPHOT_CR(:)=0.0_LDP
	END IF
C
	T1=TWOHCSQ*(NU**3)
	DO I=DST,DEND
	  T2=(T1+RJ(I))*EMHNUKT(I)*FQW/NU
	  JREC(I)=JREC(I)+T2
	  dJRECdT(I)=dJRECdT(I)+T2*HDKT*NU/T(I)/T(I)
	  JPHOT(I)=JPHOT(I)+RJ(I)*FQW/NU
	  JREC_CR(I)=JREC_CR(I)+T2*NU
	  dJREC_CRdT(I)=dJREC_CRdT(I)+T2*NU*HDKT*NU/T(I)/T(I)
	  JPHOT_CR(I)=JPHOT_CR(I)+RJ(I)*FQW
	  BPHOT_CR(I)=BPHOT_CR(I)+T1*FQW*EMHNUKT(I)/(1.0_LDP-EMHNUKT(I))
	END DO
C
	RETURN
	END
