!
! Subroutine transfers all elements N*(DST:DEND) from IN_MAT to OUT_MAT.
! IN_MAT can either be dimensioned (N,DST:DEND) (shrt) or (N,1:ND) (long).
! The OUT_MAT is asumed to be dimension (N,ND)
!
	SUBROUTINE GATHER_MAT_TO_ROOT_MPI_V1(IN_MAT,DIM1,DIM2,OUT_MAT,N,ND)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER DIM1,DIM2,N,ND
	REAL(KIND=LDP) IN_MAT(N,DIM1:DIM2)
	REAL(KIND=LDP) OUT_MAT(N,ND)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER DST,DEND
	INTEGER IERR
	INTEGER SEND_SIZE
	INTEGER NUM_DEPTHS_PER_THREAD
	INTEGER, PARAMETER :: IZERO=0
!
!	include 'mpif.h'
!
! If the send size is the same for all threads, we use the simpler gather.
!
	IF(MOD(ND,NTHREAD) .EQ. 0)THEN
	  NUM_DEPTHS_PER_THREAD=ND/NTHREAD
	  SEND_SIZE=NUM_DEPTHS_PER_THREAD*N
	  DST=NUM_DEPTHS_PER_THREAD*MYPE+1
	  CALL MPI_GATHER(IN_MAT(:,DST:),SEND_SIZE,MY_MPI_DP,
	1             OUT_MAT,SEND_SIZE,MY_MPI_DP,
	1             IZERO,MPI_COMM_WORLD,IERR)
!
	ELSE
!
	  IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	    ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	    ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	  END IF
!
! Work out send size and displacements if just sending a vector of length ND.
! We the multiply by N.
!
	  CALL SET_DST_DEND(DST,DEND,ND,NTHREAD,MYPE)
	  CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	  SCAT_DISP=SCAT_DISP*N
	  SCAT_SIZE=SCAT_SIZE*N
!
	  CALL MPI_GATHERV(IN_MAT(:,DST:),SCAT_SIZE(MYPE),MY_MPI_DP,
	1             OUT_MAT,SCAT_SIZE,SCAT_DISP,MY_MPI_DP,
	1             IZERO,MPI_COMM_WORLD,IERR)
	END IF
!
	RETURN
	END
