	SUBROUTINE GATHER_SELF_VEC_MPI_V1(OUT_VEC,DST,DEND,ND)
	USE MPI
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER DST,DEND
	REAL(KIND=LDP) OUT_VEC(ND)
	REAL(KIND=LDP) TMP_VEC(ND)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER K
	INTEGER IERR
	INTEGER NUM_DEPTHS_PER_THREAD
	INTEGER, PARAMETER ::IZERO=0
!
!	include 'mpif.h'
!
	IF(MOD(ND,NTHREAD) .EQ. 0)THEN
	  K=ND/NTHREAD  			!NUM_DEPTHS_PER_THREAD
	  CALL MPI_GATHER(OUT_VEC(DST:DEND),K,MPI_DOUBLE_PRECISION,TMP_VEC,K,MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	  IF(MYPE .EQ. 0)OUT_VEC=TMP_VEC
	ELSE
!
! Work out send size and displacements if just sending a vector of length ND.
!
	  IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	    ALLOCATE(SCAT_DISP(0:NTHREAD-1),SCAT_SIZE(0:NTHREAD-1))
	  END IF
	  CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD) 
	  CALL MPI_GATHERV(OUT_VEC(DST:DEND),SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1               TMP_VEC,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	  IF(MYPE .EQ. 0)OUT_VEC=TMP_VEC
	END IF
!
	RETURN
	END
