	SUBROUTINE GATHER_FULL_VEC_MPI_V1(OUT_VEC,IN_VEC,DST,DEND,ND)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER DST,DEND
	REAL(KIND=LDP) IN_VEC(ND)
	REAL(KIND=LDP) OUT_VEC(ND)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER K
	INTEGER IERR
	INTEGER NUM_DEPTHS_PER_THREAD
	INTEGER, PARAMETER :: IZERO=0
!
!	include 'mpif.h'
!
	IF(MOD(ND,NTHREAD) .EQ. 0)THEN
	  NUM_DEPTHS_PER_THREAD=ND/NTHREAD
	  K=NUM_DEPTHS_PER_THREAD
	  CALL MPI_GATHER(IN_VEC(DST:DEND),K,MY_MPI_DP,
	1            OUT_VEC,K,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	ELSE
!
	  IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	    ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	    ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	  END IF
!
! Work out send size and displacements if just sending a vector of length ND.
! 
	  CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	  CALL MPI_GATHERV(IN_VEC(DST:DEND),SCAT_SIZE(MYPE),MY_MPI_DP,
	1            OUT_VEC,SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
	END IF
!
	RETURN
	END
