	SUBROUTINE GATHER_ATM_MPI_V1(ND)
	USE SET_KIND_MODULE
	USE MOD_CMFGEN
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
	INTEGER, ALLOCATABLE, SAVE :: TMP_SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: TMP_SCAT_SIZE(:)
!
	INTEGER ID
	INTEGER CNT
	INTEGER K
	INTEGER, PARAMETER :: IZERO=0
!
	include 'mpif.h'
!
	ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	ALLOCATE(TMP_SCAT_DISP(0:NTHREAD-1))
	ALLOCATE(TMP_SCAT_SIZE(0:NTHREAD-1))
!
! Work out send size and displacements if just sending a vector of length ND.
!
	CNT=0
	DO K=0,NTHREAD-1
	  SCAT_DISP(K)=K*NUM_DEPTHS_PER_THREAD
	  IF(CNT+NUM_DEPTHS_PER_THREAD .GT. ND)THEN
	    SCAT_SIZE(K)=ND-CNT
	  ELSE
	    SCAT_SIZE(K)=NUM_DEPTHS_PER_THREAD
	    CNT=CNT+NUM_DEPTHS_PER_THREAD
	  END IF
	END DO
!	FLUSH(UNIT=6)
	CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
!
	DO ID=1,NUM_IONS-1
	  IF(ATM(ID)%XzV_PRES)THEN
	     CALL MPI_GATHERV(ATM(ID)%DXzV_F,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1        ROOT(ID)%DXzV_F,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	     CALL MPI_GATHERV(ATM(ID)%DXzV,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1        ROOT(ID)%DXzV,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
!
	     TMP_SCAT_DISP=SCAT_DISP*ATM(ID)%NXzV_F; TMP_SCAT_SIZE=SCAT_SIZE*ATM(ID)%NXzV_F
	     CALL MPI_GATHERV(ATM(ID)%XzV_F,TMP_SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1        ROOT(ID)%XzV_F,TMP_SCAT_SIZE,TMP_SCAT_DISP,MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
!
	     TMP_SCAT_DISP=SCAT_DISP*ATM(ID)%NXzV; TMP_SCAT_SIZE=SCAT_SIZE*ATM(ID)%NXzV
	     CALL MPI_GATHERV(ATM(ID)%XzV,TMP_SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1        ROOT(ID)%XzV,TMP_SCAT_SIZE,TMP_SCAT_DISP,MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
          END IF
        END DO
!
	DEALLOCATE(SCAT_SIZE,SCAT_DISP,TMP_SCAT_SIZE,TMP_SCAT_DISP)
!
	RETURN
	END
