	SUBROUTINE GATHER_PARTIAL_VEC_MPI_V1(VECTOR,PARTIAL_VECTOR,DST,DEND,ND)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER DST,DEND
	REAL(KIND=LDP) PARTIAL_VECTOR(DST:DEND)
	REAL(KIND=LDP) VECTOR(ND)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER, PARAMETER :: IZERO=0
	INTEGER K
	INTEGER IERR
!
!	include 'mpif.h'
!
	IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	  ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	  ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	END IF
!
! Work out send size and displacements if just sending a vector of length ND.
!
	CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	CALL MPI_GATHERV(PARTIAL_VECTOR,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1          VECTOR,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
!
	RETURN
	END
