	SUBROUTINE GATHER_VEC_TO_ROOT_MPI_V1(IN_VECTOR,OUT_VECTOR,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER ND
	REAL(KIND=LDP) IN_VECTOR(ND)
	REAL(KIND=LDP) OUT_VECTOR(ND)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER K
	INTEGER MYPE
	INTEGER IERR
	INTEGER NTHREAD
	INTEGER NUM_DEPTHS_PER_THREAD
	INTEGER, PARAMETER :: IZERO=0
!
	include 'mpif.h'
!
	CALL MPI_COMM_RANK(MPI_COMM_WORLD,MYPE,IERR)
        CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NTHREAD,IERR)
	NUM_DEPTHS_PER_THREAD=(ND-1)/NTHREAD+1
!
	IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	  ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	  ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	END IF
!
! Work out send size and displacements if just sending a vector of length ND.
!
	DO K=0,NTHREAD-1
	  SCAT_DISP(K)=K*NUM_DEPTHS_PER_THREAD
	  SCAT_SIZE(K)=NUM_DEPTHS_PER_THREAD
	  IF(SCAT_DISP(K)+SCAT_SIZE(K) .GT.  ND)SCAT_SIZE(K)=ND-SCAT_DISP(K)
	END DO
	CALL MPI_GATHERV(IN_VECTOR,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1               OUT_VECTOR,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,IZERO,
	1               MPI_COMM_WORLD,IERR)
!
	RETURN
	END
