!
! Subroutine transfers elements DST:DEND from IN_VECTOR to OUT_VECTOR.
! IN_VECTOR can either be dimensioned DST:DEND (shrt vector) or 1:ND (long vector).
! The OUT_VECTOR is asumed to have length ND.
!
	SUBROUTINE GATHER_VEC_TO_ROOT_MPI_V1(IN_VECTOR,DIM1,DIM2,OUT_VECTOR,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER DIM1,DIM2,ND
	REAL(KIND=LDP) IN_VECTOR(DIM1:DIM2)
	REAL(KIND=LDP) OUT_VECTOR(ND)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER K,DST,DEND
	INTEGER IERR
	INTEGER NUM_DEPTHS_PER_THREAD
	INTEGER, PARAMETER :: IZERO=0
!
	include 'mpif.h'
!
	CALL SET_DST_DEND(DST,DEND,ND,NTHREAD,MYPE)
!
! If the send size is the same for all threads, we use the simpler gather.
!
	IF(MOD(ND,NTHREAD) .EQ. 0)THEN
	  NUM_DEPTHS_PER_THREAD=ND/NTHREAD
	  CALL MPI_GATHER(IN_VECTOR(DST:),NUM_DEPTHS_PER_THREAD,MPI_DOUBLE_PRECISION,
	1             OUT_VECTOR,NUM_DEPTHS_PER_THREAD,MPI_DOUBLE_PRECISION,
	1             IZERO,MPI_COMM_WORLD,IERR)
!
	ELSE
!
! Work out send size and displacements if just sending a vector of length ND.
!
	  CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	  CALL MPI_GATHERV(IN_VECTOR(DST:),SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1             OUT_VECTOR,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,
	1             IZERO,MPI_COMM_WORLD,IERR)
	END IF
!
	RETURN
	END
