	SUBROUTINE GATHER_VEC_MPI_V1(VECTOR,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER ND
	REAL(KIND=LDP) VECTOR(ND)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER CNT
	INTEGER K
	INTEGER MYPE
	INTEGER IERR
	INTEGER NTHREAD
	INTEGER NUM_DEPTHS_PER_THREAD
!
	include 'mpif.h'
!
	CALL MPI_COMM_RANK(MPI_COMM_WORLD,MYPE,IERR)
        CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NTHREAD,IERR)
	NUM_DEPTHS_PER_THREAD=(ND-1)/NTHREAD+1
!
	IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	  ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	  ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	END IF
!
! Work out send size and displacements if just sending a vector of length ND.
!
	CNT=0
	DO K=0,NTHREAD-1
	  SCAT_DISP(K)=K*NUM_DEPTHS_PER_THREAD
	  IF(CNT+NUM_DEPTHS_PER_THREAD .GT. ND)THEN
	    SCAT_SIZE(K)=ND-CNT
	  ELSE
	    SCAT_SIZE(K)=NUM_DEPTHS_PER_THREAD
	    CNT=CNT+NUM_DEPTHS_PER_THREAD
	  END IF
	END DO
	CALL MPI_ALLGATHERV(MPI_IN_PLACE,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1               VECTOR,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,MPI_COMM_WORLD,IERR)
!
	RETURN
	END
