	SUBROUTINE GATHER_POPS_MPI_V1(IN_POPS,OUT_POPS,NT,DST,DEND,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER ND,NT
	INTEGER DST,DEND
	REAL(KIND=LDP) IN_POPS(NT,DST:DEND)
	REAL(KIND=LDP) OUT_POPS(NT,ND)
!
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER, PARAMETER :: IZERO=0
	INTEGER CNT
	INTEGER K
	INTEGER IERR
	INTEGER NUM_DEPTHS_PER_THREAD
!
	include 'mpif.h'
	NUM_DEPTHS_PER_THREAD=(ND-1)/NTHREAD+1
!
	IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	  ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	  ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	END IF
!
! Work out send size and displacements if just sending a vector of length ND.
!
	DO K=0,NTHREAD-1
	  SCAT_DISP(K)=K*NT*NUM_DEPTHS_PER_THREAD
	  SCAT_SIZE(K)=NT*NUM_DEPTHS_PER_THREAD
	  IF(SCAT_DISP(K)+SCAT_SIZE(K) .GT. NT*ND)SCAT_SIZE(K)=NT*ND-SCAT_DISP(K)
	END DO
	CALL MPI_GATHERV(IN_POPS,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1               OUT_POPS,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,IZERO,
	1               MPI_COMM_WORLD,IERR)
!
	RETURN
	END
