	SUBROUTINE GATHER_FAC_MATS_V1(FAC_MATS,DST,DEND,ND,MAX_SIM)
	USE SET_KIND_MODULE
	USE MPI
	USE ALLOCATE_SHARED_MPI_MEM
	IMPLICIT NONE
!
	INTEGER DST,DEND,ND
	INTEGER MAX_SIM
	REAL(KIND=LDP) FAC_MATS(ND,MAX_SIM)
!
	INTEGER I,IERR
	REAL(KIND=LDP) TEMP_MAT(MAX_SIM,2*NTHREAD)
!
	REAL(KIND=LDP), SAVE, POINTER :: TMP_VEC(:)
	REAL(KIND=LDP), SAVE, POINTER :: TMP_MAT(:,:)
        INTEGER, SAVE  :: MPI_COMM_SHARMEM, WIN
	LOGICAL, SAVE :: SHARED_MEM_ALLOCATED
!
        IF(.NOT. SHARED_MEM_ALLOCATED)THEN
          WRITE(6,*)'Allocating shared memory',MYPE;FLUSH(UNIT=6)
	  I=NTHREAD*2*MAX_SIM
          CALL SUB_ALLOCATE_DP_MPI_MEM(TMP_VEC,I,MYPE,0,MPI_COMM_WORLD,WIN)
          WRITE(6,*)'Allocated shared memory',MYPE;FLUSH(UNIT=6)
	  TMP_MAT(1:2*NTHREAD,1:MAX_SIM)=>TMP_VEC
        END IF

! Put data ins smaller array -- we only need to transfer the boudary values.
!
	TEMP_MAT(2*MYPE+1,:)=FAC_MATS(DST,:)
	TEMP_MAT(2*MYPE+2,:)=FAC_MATS(DEND,:)
	CALL MPI_WIN_FENCE(0, WIN, IERR)
!
! Do the transfer
!
!	I=2*MAX_SIM
!	CALL MPI_ALLGATHER(MPI_IN_PLACE,I,MPI_DOUBLE_PRECISION,TEMP_MAT,I,
!	1          MPI_DOUBLE_PRECISION,MPI_COMM_WORLD,IERR)
!
! Now set the values at the boundaries.
!
! NB: For a given process we have
!
	IF(MYPE .NE. 0)FAC_MATS(DST-1,:)=TEMP_MAT(2*MYPE,:)
	IF(MYPE .NE. NTHREAD-1)FAC_MATS(DEND+1,:)=TEMP_MAT(2*MYPE+3,:)
!
	RETURN
	END 
