	SUBROUTINE GATHER_POPS_MPI_V1(IN_POPS,OUT_POPS,NT,DST,DEND,ND)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER ND,NT
	INTEGER DST,DEND
	REAL(KIND=LDP) IN_POPS(NT,DST:DEND)
	REAL(KIND=LDP) OUT_POPS(NT,ND)
!
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER, PARAMETER :: IZERO=0
	INTEGER IERR
!
!	include 'mpif.h'
!
	IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	  ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	  ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	END IF
!
! Work out send size and displacements if just sending a vector of length ND.
!
	CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	SCAT_DISP=SCAT_DISP*NT; SCAT_SIZE=SCAT_SIZE*NT
	CALL MPI_GATHERV(IN_POPS,SCAT_SIZE(MYPE),MY_MPI_DP,
	1               OUT_POPS,SCAT_SIZE,SCAT_DISP,MY_MPI_DP,IZERO,
	1               MPI_COMM_WORLD,IERR)
!
	RETURN
	END
