	SUBROUTINE GATHER_VEC_MPI_V1(VECTOR,ND)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER ND
	REAL(KIND=LDP) VECTOR(ND)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER K
	INTEGER IERR
!
!	include 'mpif.h'
!
	IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	  ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	  ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	END IF
!
! Work out send size and displacements if just sending a vector of length ND.
!
	CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	CALL MPI_ALLGATHERV(MPI_IN_PLACE,SCAT_SIZE(MYPE),MY_MPI_DP,
	1               VECTOR,SCAT_SIZE,SCAT_DISP,MY_MPI_DP,MPI_COMM_WORLD,IERR)
!
	RETURN
	END
