	SUBROUTINE GATHER_FAC_MATS_V1(FAC_MATS,DST,DEND,ND,MAX_SIM)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER DST,DEND,ND
	INTEGER MAX_SIM
	REAL(KIND=LDP) FAC_MATS(ND,MAX_SIM)
!
	INTEGER I,IERR
	REAL(KIND=LDP) TEMP_MAT(MAX_SIM,2*NTHREAD)
!
! Put data ins smaller array -- we only need to transfer the boudary values.
!
	TEMP_MAT(:,2*MYPE+1)=FAC_MATS(DST,:)
	TEMP_MAT(:,2*MYPE+2)=FAC_MATS(DEND,:)
!
! Do the transfer
!
	I=2*MAX_SIM
	CALL MPI_ALLGATHER(MPI_IN_PLACE,I,MPI_DOUBLE_PRECISION,TEMP_MAT,I,
	1          MPI_DOUBLE_PRECISION,MPI_COMM_WORLD,IERR)
!
! Now set the values at the boundaries.
!
! NB: For a given process we have
!
	IF(MYPE .NE. 0)FAC_MATS(DST-1,:)=TEMP_MAT(:,2*MYPE)
	IF(MYPE .NE. NTHREAD-1)FAC_MATS(DEND+1,:)=TEMP_MAT(:,2*MYPE+3)
!
	RETURN
	END 
