	SUBROUTINE ROOT_GATHERV_VEC_MPI_V1(VECTOR,ND)
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER ND
	REAL(KIND=LDP) VECTOR(ND)
	REAL(KIND=LDP), ALLOCATABLE::  OUT_VECTOR(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER K,LOC
	INTEGER MYPE
	INTEGER IERR
	INTEGER NTHREAD
	INTEGER NUM_DEPTHS_PER_THREAD
!
	include 'mpif.h'
!
	CALL MPI_COMM_RANK(MPI_COMM_WORLD,MYPE,IERR)
        CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NTHREAD,IERR)
	NUM_DEPTHS_PER_THREAD=(ND-1)/NTHREAD+1
!
	IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	  ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	  ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	END IF
!
! Work out send size and displacements if just sending a vector of length ND.
!
	DO K=0,NTHREAD-1
	  SCAT_DISP(K)=K*NUM_DEPTHS_PER_THREAD
	  SCAT_SIZE(K)=NUM_DEPTHS_PER_THREAD
	  IF(SCAT_DISP(K)+SCAT_SIZE(K) .GT. ND)SCAT_SIZE(K)=ND-SCAT_DISP(K)
	END DO
!
	IF(MYPE .EQ. 0)THEN
	  ALLOCATE(OUT_VECTOR(ND))
	ELSE
	  ALLOCATE(OUT_VECTOR(1))
	END IF
	K=0; LOC=SCAT_DISP(MYPE)+1
	CALL MPI_GATHERV(VECTOR(LOC),SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1          OUT_VECTOR,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,K,MPI_COMM_WORLD,IERR)
	IF(MYPE .EQ. 0)VECTOR=OUT_VECTOR
	DEALLOCATE(OUT_VECTOR)
!
	RETURN
	END
