	SUBROUTINE SCATTER_XZV_F_AND_IONS(ND)
	USE MOD_CMFGEN
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER, ALLOCATABLE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE :: SCAT_SIZE(:)
!
	INTEGER ID
	INTEGER K
	INTEGER, PARAMETER :: IZERO=0
!
	include 'mpif.h'
!
	CALL MPI_COMM_RANK(MPI_COMM_WORLD,MYPE,IERR)
!
	NUM_DEPTHS_PER_THREAD=(ND-1)/NTHREAD+1
	ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
!
! Work out send size and displacements if just sending a vector of length ND.
!
	DO K=0,NTHREAD-1
	  SCAT_DISP(K)=K*NUM_DEPTHS_PER_THREAD
	  SCAT_SIZE(K)=NUM_DEPTHS_PER_THREAD
	  IF(SCAT_DISP(K)+SCAT_DISP(K) .GT.  ND)SCAT_SIZE(K)=ND-SCAT_DISP(K)
	END DO
	FLUSH(UNIT=6)
!	IF(MYPE .EQ. 0)WRITE(6,*)1,SIZE(ROOT(1)%DXzV_F),SIZE(ATM(1)%DXzV_F)
!	IF(MYPE .EQ. 0)WRITE(6,*)1,SIZE(ROOT(2)%DXzV_F),SIZE(ATM(2)%DXzV_F)
!	IF(MYPE .EQ. 0)WRITE(6,*)1,SIZE(ROOT(3)%DXzV_F),SIZE(ATM(3)%DXzV_F)
	CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
!
	DO ID=1,NUM_IONS-1
	  IF(ATM(ID)%XzV_PRES)THEN
	    WRITE(6,*)'ID,MYPE,DST,DEND=',ID,MYPE,DST,DEND
	    IF(MYPE .EQ. 0)THEN
	      WRITE(6,*)'ROOT=',MYPE,ROOT(ID)%DXzV_F(1),ROOT(ID)%DXzV_F(ND)
	    END IF
	    FLUSH(UNIT=6)
	     CALL MPI_SCATTERV(ROOT(ID)%DXzV_F,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,
	1        ATM(ID)%DXzV_F,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	     SCAT_DISP=SCAT_DISP*ATM(ID)%NXzV_F; SCAT_SIZE=SCAT_SIZE*ATM(ID)%NXzV_F
	     CALL MPI_SCATTERV(ROOT(ID)%XzV_F,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,
	1        ATM(ID)%XzV_F,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	     SCAT_DISP=SCAT_DISP/ATM(ID)%NXzV_F; SCAT_SIZE=SCAT_SIZE/ATM(ID)%NXzV_F
	    WRITE(6,*)'MYPE=',MYPE,ATM(ID)%DXzV_F(DST),ATM(ID)%DXzV_F(DEND)
	    FLUSH(UNIT=6)
          END IF
        END DO
!
	DEALLOCATE(SCAT_SIZE,SCAT_DISP)
!
	RETURN
	END
