	SUBROUTINE SCATTER_XZV_F_AND_IONS(ND)
	USE SET_KIND_MODULE
	USE MOD_CMFGEN
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER, ALLOCATABLE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE :: SCAT_SIZE(:)
!
	INTEGER ID
	INTEGER K
	INTEGER, PARAMETER :: IZERO=0
!
	include 'mpif.h'
!
	ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
!
! Work out send size and displacements if just sending a vector of length ND.
!
	CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
!
	DO ID=1,NUM_IONS-1
	  IF(ATM(ID)%XzV_PRES)THEN
	     CALL MPI_SCATTERV(ROOT(ID)%DXzV_F,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,
	1        ATM(ID)%DXzV_F,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	     CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
	     SCAT_DISP=SCAT_DISP*ATM(ID)%NXzV_F; SCAT_SIZE=SCAT_SIZE*ATM(ID)%NXzV_F
	     CALL MPI_SCATTERV(ROOT(ID)%XzV_F,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,
	1        ATM(ID)%XzV_F,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,IZERO,MPI_COMM_WORLD,IERR)
	     CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
	     SCAT_DISP=SCAT_DISP/ATM(ID)%NXzV_F; SCAT_SIZE=SCAT_SIZE/ATM(ID)%NXzV_F
          END IF
        END DO
	DEALLOCATE(SCAT_SIZE,SCAT_DISP)
!
	RETURN
	END
