	MODULE MOD_RAY_MOM_STORE
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
! Altered 10-Feb-2026  -- RSQH_IB_PNT_SRCE added to module.
!                         SAVE statement was added.
!
	INTEGER ND_STORE
	REAL(KIND=LDP), ALLOCATABLE :: R_STORE(:)
	REAL(KIND=LDP), ALLOCATABLE :: RMID_STORE(:)
	REAL(KIND=LDP), ALLOCATABLE :: EXT_RMID_STORE(:)
	REAL(KIND=LDP), ALLOCATABLE :: JNU_STORE(:)
	REAL(KIND=LDP), ALLOCATABLE :: HNU_STORE(:)
	REAL(KIND=LDP), ALLOCATABLE :: NNU_STORE(:)
	REAL(KIND=LDP), ALLOCATABLE :: KNU_STORE(:)
	REAL(KIND=LDP), ALLOCATABLE :: GAM_REL_STORE(:)
!
! General description of radiation field at boundaries.
!
	REAL(KIND=LDP) JPLUS_IB,JMIN_IB
	REAL(KIND=LDP) HPLUS_IB,HMIN_IB
	REAL(KIND=LDP) KPLUS_IB,KMIN_IB
	REAL(KIND=LDP) NPLUS_IB,NMIN_IB
	REAL(KIND=LDP) JPLUS_OB,JMIN_OB
	REAL(KIND=LDP) HPLUS_OB,HMIN_OB
	REAL(KIND=LDP) KPLUS_OB,KMIN_OB
	REAL(KIND=LDP) NPLUS_OB,NMIN_OB
!
	REAL(KIND=LDP) HNU_AT_OB, NNU_AT_OB
	REAL(KIND=LDP) HNU_AT_IB, NNU_AT_IB
	REAL(KIND=LDP) HNU_AT_OB_PREV, NNU_AT_OB_PREV
	REAL(KIND=LDP) HNU_AT_IB_PREV, NNU_AT_IB_PREV
	REAL(KIND=LDP) :: RSQH_IB_PNT_SRCE=0.0D0
!
	REAL(KIND=LDP) HBC,HBC_PREV,HBC_SAVE
	REAL(KIND=LDP) NBC,NBC_PREV,NBC_SAVE
	REAL(KIND=LDP) IN_HBC,IN_HBC_PREV,IN_HBC_SAVE
!
	REAL(KIND=LDP), ALLOCATABLE :: RMID(:)
	REAL(KIND=LDP), ALLOCATABLE :: H_ON_J(:)
	REAL(KIND=LDP), ALLOCATABLE :: N_ON_J(:)
	REAL(KIND=LDP), ALLOCATABLE :: K_ON_J(:)
	REAL(KIND=LDP), ALLOCATABLE :: KMID_ON_J(:)
	REAL(KIND=LDP), ALLOCATABLE :: NMID_ON_J(:)
	REAL(KIND=LDP), ALLOCATABLE :: NMID_ON_HMID(:)
	REAL(KIND=LDP), ALLOCATABLE :: dlnGRSQJdlnR(:)
!
	REAL(KIND=LDP), ALLOCATABLE :: H_ON_J_PREV(:)
	REAL(KIND=LDP), ALLOCATABLE :: N_ON_J_PREV(:)
	REAL(KIND=LDP), ALLOCATABLE :: K_ON_J_PREV(:)
	REAL(KIND=LDP), ALLOCATABLE :: KMID_ON_J_PREV(:)
	REAL(KIND=LDP), ALLOCATABLE :: NMID_ON_J_PREV(:)
	REAL(KIND=LDP), ALLOCATABLE :: NMID_ON_HMID_PREV(:)
!
	REAL(KIND=LDP), ALLOCATABLE :: H_ON_J_SAVE(:)
	REAL(KIND=LDP), ALLOCATABLE :: N_ON_J_SAVE(:)
	REAL(KIND=LDP), ALLOCATABLE :: K_ON_J_SAVE(:)
	REAL(KIND=LDP), ALLOCATABLE :: KMID_ON_J_SAVE(:)
	REAL(KIND=LDP), ALLOCATABLE :: NMID_ON_J_SAVE(:)
	REAL(KIND=LDP), ALLOCATABLE :: NMID_ON_HMID_SAVE(:)
!
	LOGICAL HN_DEF_ON_NODES
!
	SAVE
	END MODULE MOD_RAY_MOM_STORE
