	MODULE MOD_VAR_JREL_MPI_V1
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
! These vectors must be saved as they will be used on subsequent iterations.
!
	REAL(KIND=LDP), ALLOCATABLE :: AV_SIGMA(:)
	REAL(KIND=LDP), ALLOCATABLE :: BETA(:)
	REAL(KIND=LDP), ALLOCATABLE :: BETA_FREQ(:)
	REAL(KIND=LDP), ALLOCATABLE :: GAM_RSQ(:)
	REAL(KIND=LDP), ALLOCATABLE :: GAM_REL(:)
	REAL(KIND=LDP), ALLOCATABLE :: GAM_REL_SQ(:)
	REAL(KIND=LDP), ALLOCATABLE :: CON_DELTA(:)
	REAL(KIND=LDP), ALLOCATABLE :: CON_DELTAH(:)
	REAL(KIND=LDP), ALLOCATABLE :: CON_dKdNUH(:)
	REAL(KIND=LDP), ALLOCATABLE :: CON_dNdNUH(:)
	REAL(KIND=LDP), ALLOCATABLE :: CON_dKdNU(:)
	REAL(KIND=LDP), ALLOCATABLE :: CON_dHdNU(:)
!
	REAL(KIND=LDP), ALLOCATABLE :: JNU(:)
	REAL(KIND=LDP), ALLOCATABLE :: JNU_PREV(:)
        REAL(KIND=LDP), ALLOCATABLE :: GAM_RSQHNU(:)
        REAL(KIND=LDP), ALLOCATABLE :: GAM_RSQHNU_PREV(:)
!
	REAL(KIND=LDP), TARGET, ALLOCATABLE :: TRI_VECS(:,:)
	REAL(KIND=LDP), ALLOCATABLE :: TRI_VECS_SAVE(:,:)
	REAL(KIND=LDP), POINTER :: TA(:)
	REAL(KIND=LDP), POINTER :: TB(:)
	REAL(KIND=LDP), POINTER :: TC(:)
	REAL(KIND=LDP), POINTER :: XM(:)
!
	REAL(KIND=LDP), TARGET, ALLOCATABLE :: SET_UP_VECS(:,:)
	REAL(KIND=LDP), POINTER :: EPS_A(:),EPS_B(:)
	REAL(KIND=LDP), POINTER :: EPS_PREV_A(:),EPS_PREV_B(:)
	REAL(KIND=LDP), POINTER :: PSIPREV(:)
	REAL(KIND=LDP), POINTER :: HU(:),HL(:),HS(:)
!	
	REAL(KIND=LDP), ALLOCATABLE :: GAM_RSQ_DTAUONQ(:)
	REAL(KIND=LDP), ALLOCATABLE :: DELTA(:),DELTAH(:)
	REAL(KIND=LDP), ALLOCATABLE :: W(:),WPREV(:)
	REAL(KIND=LDP), ALLOCATABLE :: PSI(:)
	REAL(KIND=LDP), ALLOCATABLE :: PSIPREV_MOD(:)
	REAL(KIND=LDP), ALLOCATABLE :: CHI_H(:),CHI_J(:)
	REAL(KIND=LDP), ALLOCATABLE :: DTAU_H(:),DTAU_J(:)
	REAL(KIND=LDP), ALLOCATABLE :: Q(:),SOURCE(:)
	REAL(KIND=LDP), ALLOCATABLE :: VB(:),VC(:),COH_VEC(:)
	REAL(KIND=LDP), ALLOCATABLE :: P_H(:),P_J(:)
	REAL(KIND=LDP), ALLOCATABLE :: VdJdR_TERM(:),VdHdR_TERM(:)
	REAL(KIND=LDP), ALLOCATABLE :: GAM_RSQJNU_PREV(:)
!
	REAL(KIND=LDP), ALLOCATABLE :: TX_OLD_d_T(:)
	REAL(KIND=LDP), ALLOCATABLE :: TX_OLD_d_dTdR(:)
!
! These vectors are used by EDD_JREL_VAR_V1
!
	REAL(KIND=LDP), ALLOCATABLE :: dTAUdCHI_H(:,:)
	REAL(KIND=LDP), ALLOCATABLE :: dTAUdCHI_J(:,:)
	REAL(KIND=LDP), ALLOCATABLE :: dHUdCHI(:)
	REAL(KIND=LDP), ALLOCATABLE :: dHLdCHI(:)
	REAL(KIND=LDP), ALLOCATABLE :: dHSdCHI(:)
	REAL(KIND=LDP), ALLOCATABLE :: dHUdTAU(:)
	REAL(KIND=LDP), ALLOCATABLE :: dHLdTAU(:)
	REAL(KIND=LDP), ALLOCATABLE :: EPS_FAC(:)
	REAL(KIND=LDP), ALLOCATABLE :: dRHSdI(:)
	REAL(KIND=LDP), ALLOCATABLE :: dRHSdJ(:)
	REAL(KIND=LDP), ALLOCATABLE :: DERIV_SCL_FAC(:)
!
	INTEGER N_SET_UP_VECS
	INTEGER VEC_LENGTH
	INTEGER ND_SAV
!
	SAVE
	END MODULE MOD_VAR_JREL_MPI_V1
!
! Subroutine to allocate the required vectors.
!
	SUBROUTINE ALLOC_MOD_VAR_JREL_MPI_V1(ND)
	USE SET_KIND_MODULE
	USE MOD_VAR_JREL_MPI_V1
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER IOS,I
	INTEGER LUER,ERROR_LU
	EXTERNAL ERROR_LU
!
	LUER=ERROR_LU()
!
	IF(.NOT. ALLOCATED(AV_SIGMA))THEN
!
	  ND_SAV=ND
	  ALLOCATE (AV_SIGMA(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (BETA(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (BETA_FREQ(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (GAM_RSQ(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (GAM_REL(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (GAM_REL_SQ(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (CON_DELTA(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (CON_DELTAH(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (CON_dKdNUH(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (CON_dNdNUH(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (CON_dKdNU(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (CON_dHdNU(ND),STAT=IOS)
	  IF(IOS .NE. 0)THEN
	    WRITE(LUER,*)'Unable to allocate memory(1) in ALLOC_MOD_J_REL'
	    WRITE(LUER,*)'STAT=',IOS
	    STOP
	  END IF
!
          IF(IOS .EQ. 0)ALLOCATE (JNU(ND),STAT=IOS)
          IF(IOS .EQ. 0)ALLOCATE (JNU_PREV(ND),STAT=IOS)
          IF(IOS .EQ. 0)ALLOCATE (GAM_RSQHNU(ND),STAT=IOS)
          IF(IOS .EQ. 0)ALLOCATE (GAM_RSQHNU_PREV(ND),STAT=IOS)
	  IF(IOS .NE. 0)THEN
	    WRITE(LUER,*)'Unable to allocate memory(2) in ALLOC_MOD_J_REL'
	    WRITE(LUER,*)'STAT=',IOS
	    STOP
	  END IF
!
	  VEC_LENGTH=4*ND
	  IF(.NOT. ALLOCATED(TRI_VECS))THEN
	    ALLOCATE (TRI_VECS(ND,4),STAT=IOS)
	    ALLOCATE (TRI_VECS_SAVE(ND,4),STAT=IOS)
	  END IF
	  TRI_VECS=0.0_LDP
	  TA(1:ND)=>TRI_VECS(1:ND,1)
	  TB(1:ND)=>TRI_VECS(1:ND,2)
	  TC(1:ND)=>TRI_VECS(1:ND,3)
	  XM(1:ND)=>TRI_VECS(1:ND,4)
!
	  N_SET_UP_VECS=8
	  VEC_LENGTH=N_SET_UP_VECS*ND
	  IF(.NOT. ALLOCATED(SET_UP_VECS))THEN
	    ALLOCATE (SET_UP_VECS(ND,N_SET_UP_VECS),STAT=IOS)
	  END IF
	  SET_UP_VECS=0.0_LDP; I=0
	  I=I+1; HL(1:ND)=>SET_UP_VECS(1:ND,I)
	  I=I+1; HU(1:ND)=>SET_UP_VECS(1:ND,I)
	  I=I+1; HS(1:ND)=>SET_UP_VECS(1:ND,I)
	  I=I+1; EPS_A(1:ND)=>SET_UP_VECS(1:ND,I)
	  I=I+1; EPS_B(1:ND)=>SET_UP_VECS(1:ND,I)
	  I=I+1; EPS_PREV_A(1:ND)=>SET_UP_VECS(1:ND,I)
	  I=I+1; EPS_PREV_B(1:ND)=>SET_UP_VECS(1:ND,I)
	  I=I+1; PSIPREV(1:ND)=>SET_UP_VECS(1:ND,I)
	  IF(I .NE. N_SET_UP_VECS)THEN
	    WRITE(6,*)'Error in mod_var_jrel_mpi_v1.f'
	    WRITE(6,*)'Incorrect number of set_up_vectors'
	    STOP
	  END IF
!
	  ALLOCATE (CHI_H(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (CHI_J(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (DTAU_H(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (DTAU_J(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (Q(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (SOURCE(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (VB(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (VC(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (COH_VEC(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (PSI(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (PSIPREV_MOD(ND),STAT=IOS)
	  IF(IOS .NE. 0)THEN
	    WRITE(LUER,*)'Unable to allocate memory(3) in ALLOC_MOD_VAR_JREL'
	    WRITE(LUER,*)'STAT=',IOS
	    STOP
	  END IF
!
	  IF(IOS .EQ. 0)ALLOCATE (GAM_RSQ_DTAUONQ(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (P_H(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (P_J(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (VdJdR_TERM(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (VdHdR_TERM(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (DELTA(ND),STAT=IOS)
          IF(IOS .EQ. 0)ALLOCATE (DELTAH(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (W(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (WPREV(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (TX_OLD_d_T(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (TX_OLD_d_dTdR(ND),STAT=IOS)
	  IF(IOS .NE. 0)THEN
	    WRITE(LUER,*)'Unable to allocate memory(4) in ALLOC_MOD_VAR_JREL'
	    WRITE(LUER,*)'STAT=',IOS
	    STOP
	  END IF
!
	  IF(IOS .EQ. 0)ALLOCATE(dTAUdCHI_H(ND,ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(dTAUdCHI_J(ND,ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(dHUdCHI(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(dHLdCHI(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(dHSdCHI(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(dHUdTAU(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(dHLdTAU(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(EPS_FAC(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(dRHSdI(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(dRHSdJ(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE(DERIV_SCL_FAC(ND),STAT=IOS); DERIV_SCL_FAC=1.0_LDP
	  IF(IOS .NE. 0)THEN
	    WRITE(LUER,*)'Unable to allocate memory(5) in ALLOC_MOD_VAR_JREL'
	    WRITE(LUER,*)'STAT=',IOS
	    STOP
	  END IF
	END IF
!
        JNU_PREV(:)=0.0_LDP
        GAM_RSQHNU_PREV(:)=0.0_LDP
!
	IF(ND_SAV .EQ. ND)THEN
	  RETURN
	ELSE
	  WRITE(LUER,*)'Error in ALLOC_MOD_VAR_JREL'
	  WRITE(LUER,*)'At present allocation size cannot be changed'
	  WRITE(LUER,*)'Need to modify ALLOC_MOD_VAR_JREL'
	  STOP
	END IF
!
	RETURN
	END
