        MODULE MOD_VAR_MOM_J_CMF_MPI_V1
	USE SET_KIND_MODULE
	IMPLICIT NONE
!
	INTEGER VEC_LENGTH
	REAL(KIND=LDP), POINTER :: TA(:)
	REAL(KIND=LDP), POINTER :: TB(:)
	REAL(KIND=LDP), POINTER :: TC(:)
	REAL(KIND=LDP), POINTER :: XM(:)
	REAL(KIND=LDP), TARGET, ALLOCATABLE :: TRI_VECS(:,:)
!
	INTEGER N_SET_UP_VECS
	REAL(KIND=LDP), TARGET, ALLOCATABLE :: SET_UP_VECS(:,:)
	REAL(KIND=LDP), POINTER :: GAM(:)
	REAL(KIND=LDP), POINTER :: GAMH(:)
	REAL(KIND=LDP), POINTER :: W(:)
	REAL(KIND=LDP), POINTER :: WPREV(:)
	REAL(KIND=LDP), POINTER :: PSI(:)
	REAL(KIND=LDP), POINTER :: PSIPREV(:)
	REAL(KIND=LDP), POINTER :: EPS_A(:)
	REAL(KIND=LDP), POINTER :: EPS_B(:)
	REAL(KIND=LDP), POINTER :: EPS_PREV_A(:)
	REAL(KIND=LDP), POINTER :: EPS_PREV_B(:)
	REAL(KIND=LDP), POINTER :: VB(:)
	REAL(KIND=LDP), POINTER :: VC(:)
	REAL(KIND=LDP), POINTER :: HU(:)
	REAL(KIND=LDP), POINTER :: HL(:)
	REAL(KIND=LDP), POINTER :: HS(:)
!
	REAL(KIND=LDP), ALLOCATABLE :: DTAU(:)
	REAL(KIND=LDP), ALLOCATABLE :: RSQ_DTAUONQ(:)
	REAL(KIND=LDP), ALLOCATABLE :: SOURCE(:)
	REAL(KIND=LDP), ALLOCATABLE :: Q(:)
	REAL(KIND=LDP), ALLOCATABLE :: JNU(:)
	REAL(KIND=LDP), ALLOCATABLE :: RSQ_HNU(:)
	REAL(KIND=LDP), ALLOCATABLE :: TX_OLD_d_T(:)
	REAL(KIND=LDP), ALLOCATABLE :: TX_OLD_d_dTdR(:)
	REAL(KIND=LDP), ALLOCATABLE :: JNUM1(:)
	REAL(KIND=LDP), ALLOCATABLE :: RSQ_HNUM1(:)
	REAL(KIND=LDP), ALLOCATABLE :: PSIPREV_MOD(:)
!
	END MODULE MOD_VAR_MOM_J_CMF_MPI_V1
!
	SUBROUTINE MOD_VAR_MOM_ALLOC_MPI_V1(ND)
	USE SET_KIND_MODULE
	USE MOD_VAR_MOM_J_CMF_MPI_V1
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER IOS
	INTEGER LUER
	INTEGER ERROR_LU
	EXTERNAL ERROR_LU
!
	IF(.NOT. ALLOCATED(DTAU))THEN
	  ALLOCATE(DTAU(ND),RSQ_DTAUONQ(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (SOURCE(ND),Q(ND),JNU(ND),RSQ_HNU(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (PSIPREV_MOD(ND),STAT=IOS)
	  IF(IOS .EQ. 0)ALLOCATE (TX_OLD_d_T(ND),TX_OLD_d_dTdR(ND),STAT=IOS)
!
! NB: JNUM1 and RSQHNUM1 must not be zeroed in the routine.
!
	  IF(IOS .EQ. 0)ALLOCATE (JNUM1(ND),RSQ_HNUM1(ND),STAT=IOS)
	  VEC_LENGTH=ND
!
	  IF(IOS .NE. 0)THEN
	    LUER=ERROR_LU()
	    WRITE(LUER,*)'Unable to allocate memory in MOD_VAR_MOM_ALLOC'
	    WRITE(LUER,*)'STAT=',IOS
	    STOP
	  END IF
	END IF
!
	IF(.NOT. ALLOCATED(TRI_VECS))THEN
	  ALLOCATE (TRI_VECS(ND,4),STAT=IOS)
	END IF
	TRI_VECS=0.0_LDP
	TA(1:ND)=>TRI_VECS(1:ND,1)
	TB(1:ND)=>TRI_VECS(1:ND,2)
	TC(1:ND)=>TRI_VECS(1:ND,3)
	XM(1:ND)=>TRI_VECS(1:ND,4)
!
	N_SET_UP_VECS=15
	IF(.NOT. ALLOCATED(SET_UP_VECS))THEN
	  ALLOCATE (SET_UP_VECS(ND,N_SET_UP_VECS),STAT=IOS)
	END IF
	SET_UP_VECS=0.0_LDP
	GAM=>SET_UP_VECS(:,1)
	GAMH=>SET_UP_VECS(:,2)
	W=>SET_UP_VECS(:,3)
	WPREV=>SET_UP_VECS(:,4)
	PSI=>SET_UP_VECS(:,5)
	PSIPREV=>SET_UP_VECS(:,6)
	EPS_A=>SET_UP_VECS(:,7)
	EPS_B=>SET_UP_VECS(:,8)
	EPS_PREV_A=>SET_UP_VECS(:,9)
	EPS_PREV_B=>SET_UP_VECS(:,10)
	VB=>SET_UP_VECS(:,11)
	VC=>SET_UP_VECS(:,12)
	HU=>SET_UP_VECS(:,13)
	HL=>SET_UP_VECS(:,14)
	HS=>SET_UP_VECS(:,15)
!
! Initialize all vectors.
!
	TA=0.0_LDP; TB=0.0_LDP; TC=0.0_LDP; DTAU=0.0_LDP; RSQ_DTAUONQ=0.0_LDP
	XM=0.0_LDP; SOURCE=0.0_LDP; Q=0.0_LDP; JNU=0.0_LDP; RSQ_HNU=0.0_LDP
	TX_OLD_d_T=0.0_LDP; TX_OLD_d_dTdR=0.0_LDP
!
	RETURN
	END	
