	SUBROUTINE SET_PNT_SOURCE_RAD(INTEN,RSQH_IB_PNT_SRCE,FREQ,R_PNT_SRCE,R_IB)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	REAL(KIND=LDP) INTEN
	REAL(KIND=LDP) RSQH_IB_PNT_SRCE
	REAL(KIND=LDP) FREQ
	REAL(KIND=LDP) R_PNT_SRCE
	REAL(KIND=LDP) R_IB
!
	REAL(KIND=LDP), SAVE :: R_PNT
	REAL(KIND=LDP), SAVE :: TEFF_PNT
	REAL(KIND=LDP), SAVE :: T1
!
	INTEGER LUIN, LUSCR, IOS
	INTEGER, PARAMETER :: ITEN=10
	LOGICAL, SAVE :: FIRST=.TRUE.
	CHARACTER(LEN=10) TYPE_PNT
	LOGICAL, PARAMETER :: L_TRUE=.TRUE.
!
! Constants for opacity etc. These are set in CMFGEN.
!
        COMMON/CONSTANTS/ CHIBF,CHIFF,HDKT,TWOHCSQ
        COMMON/LINE/ OPLIN,EMLIN
        REAL(KIND=LDP) CHIBF,CHIFF,HDKT,TWOHCSQ
        REAL(KIND=LDP) OPLIN,EMLIN
!
! MPI related data
!
        INTEGER IERR
        INTEGER ERRORCODE
!
	IF(FIRST)THEN
	  TEFF_PNT=0.0_LDP
	  CALL GET_LU(LUIN,'SET_POINT_SOURCE_RAD -- LUIN')
	  OPEN(UNIT=LUIN,FILE='POINT_SOURCE_DATA',STATUS='OLD',ACTION='READ',IOSTAT=IOS)
	    IF(IOS .NE. 0)THEN
	      WRITE(6,*)'Error opening POINT_SOURCE_DATA in SET_PNT_SOURCE_RAD'
	      STOP
	     END IF
!
! Can only get LUSCR after file assoicated with LUIN has been opened.
!
	    CALL GET_LU(LUSCR,'SET_POINT_SOURCE_RAD -- LUSRC')
	    CALL RD_OPTIONS_INTO_STORE(LUIN,LUSCR)
	    CALL RD_STORE_NCHAR(TYPE_PNT,'TYPE_PNT',ITEN,L_TRUE,'Type of point source controll')
	    IF(TYPE_PNT .EQ. 'BB')THEN
	      CALL RD_STORE_DBLE(TEFF_PNT,'TEFF_PNT',L_TRUE,'Effective temp (units 10^4 K')
	    ELSE
	      WRITE(6,*)'Error in SET_POINT_SOURCE_RAD -- unrecognized option - MYPE=',MYPE
	      CALL MPI_ABORT(MPI_COMM_WORLD,ERRORCODE,IERR)
	     END IF
	    CALL CLEAN_RD_STORE()
	  CLOSE(LUIN); CLOSE(LUSCR)
	  FIRST=.FALSE.
	  IF(MYPE .EQ. 0)THEN
	    WRITE(6,'(/,1X,A)')'Using POINT source model'
	    T1=( (R_PNT_SRCE/6.96)**2 )*(TEFF_PNT/0.5772)**4
	    WRITE(6,'(1X,A,ES12.4,/)')'Luminosity of model is (in Lsun)',T1
	    FLUSH(UNIT=6)
	  END IF 
	END IF
!
	T1=EXP(-HDKT*FREQ/TEFF_PNT)
	INTEN=TWOHCSQ*(FREQ**3)*T1/(1.0_LDP-T1)
	RSQH_IB_PNT_SRCE=INTEN*(R_PNT_SRCE/R_IB)**2
!
	RETURN
	END	
