!
! The first subroutines gathers all the change exchange cooling rates
! and sends the to the ROOT process.
!
	SUBROUTINE READY_CHG_COOL_WR(ND)
	USE SET_KIND_MODULE
	USE CHG_EXCH_MOD_V3
	USE MPI
	IMPLICIT NONE
!
	INTEGER ND
        INTEGER ISEND(0:NTHREAD-1)
        INTEGER IDISP(0:NTHREAD-1)
	INTEGER IERR
	INTEGER, PARAMETER :: IZERO=0
!
	IF(MYPE .EQ. 0)ALLOCATE(ROOT_COOL_CHG(N_CHG,ND))
	CALL SET_IDISP_ISEND(IDISP,ISEND,ND,NTHREAD)
	IDISP=IDISP*N_CHG
	ISEND=ISEND*N_CHG
	CALL MPI_GATHERV(COOL_CHG,ISEND(MYPE),MY_MPI_DP,ROOT_COOL_CHG,ISEND,IDISP,
	1                    MY_MPI_DP,IZERO,MPI_COMM_WORLD,IERR)
!
	RETURN
	END
!
! Routine to write out cooling/heating for charge exchange reactions.
!
	SUBROUTINE WR_CHG_COOL_MPI_V1(NETCR,TOTCR,COUNTER,ND,LU)
	USE SET_KIND_MODULE
	USE CHG_EXCH_MOD_V3
	IMPLICIT NONE
!
! Altered 03-Oct-2011 : Checks on non-zero N_CHG before writing header.
! Created 26-Aug-1998 : based on WR_AD_COOL
!
	INTEGER COUNTER
	INTEGER ND,LU
	REAL(KIND=LDP) NETCR(ND)	!Accumlated net cooling rate
	REAL(KIND=LDP) TOTCR(ND)	!Accumulated sum of absoulte cooling rates.
!
	INTEGER I,J
	INTEGER MS,MF
!
	IF(.NOT. DO_CHG_EXCH)RETURN
	IF(N_CHG .EQ. 0)RETURN
!
	IF(MYPE .EQ. 0 .AND. .NOT. ALLOCATED(ROOT_COOL_CHG))THEN
	  WRITE(6,*)'Error calling WR_CHG_COOL_MPI_V1'
	  WRITE(6,*)'Need to first call READY_CHG_COOL_WR' 
	END IF
!
	MS=(COUNTER-1)*10+1	
	MF=COUNTER*10
	IF(MF .GT. ND)MF=ND
!
	WRITE(LU,'(/3X,A)')'Charge exchange cooling rate [ergs/cm**3/sec]'
	DO J=1,N_CHG
	  IF(CHG_REACTION_AVAILABLE(J))THEN
	    DO I=MS,MF
	      NETCR(I)=NETCR(I)+ROOT_COOL_CHG(J,I)
	      TOTCR(I)=TOTCR(I)+ABS(ROOT_COOL_CHG(J,I))
	    END DO
	    WRITE(LU,999)(ROOT_COOL_CHG(J,I),I=MS,MF)
	  END IF
	END DO
!
999	FORMAT(1X,1P,10E12.4)
	RETURN
	END
