	PROGRAM SCATER_XZV_F_AND_IONS(ND)
	USE MOD_CMFGEN
	IMPLICIT NONE
!
	INTEGER ND
	INTEGER, ALLOCATABE :: SCAT_DISP(:)
	INTEGER, ALLOCATABE :: SCAT_SIZE(:)
!
	include 'mpi.h'
	INTEGER NTHREAD
	INTEGER NUM_DEPTHS_PER_THREAD
	INTEGER MYPE
	INTEGER ID
	INTEGER CNT
	INTEGER K
!
	CALL MPI_COMM_RANK(MPI_COMM_WORLD,MYPE,IERR)
	CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NTHREAD,IERR)
!
	NUM_DEPTHS_PER_THREAD=(ND-1)/NTHREAD+1
	ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
!
! Work out send size and displacements if just sending a vector of length ND.
!
	CNT=0
	DO K=0,NTHREAD-1
	  SCAT_DISP(K)=K*NUM_DEPTHS_PER_THREAD
	  IF(CNT+NUM_DEPTHS_PER_THREAD .GT. ND)THEN
	    SCAT_SIZE(K)=ND-CNT
	  ELSE
	    SCAT_SIZE(K)=NUM_DEPTHS_PER_THREAD
	    CNT=CNT+NUM_DEPTHS_PER_THREAD
	  END IF
	END DO
!
	DO ID=1,NUM_IONS-1
          IF(ATM(ID)%XzV_PRES)THEN
	     CALL MPI_SCATTERV(ROOT(ID)%DXzV_F,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISSION,
	1        ATM(ID)%DXzV_F,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISSION,IZERO,MPI_COMM_WORLD)
	     SCAT_DISP=SCAT_DISP*ATM(ID)%XzVF_F; SCAT_SIZE=SCAT_SIZE*ATM(ID)%XzVF_F
	     CALL MPI_SCATTERV(ROOT(ID)%XzV_F,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISSION,
	1        ATM(ID)%XzV_F,SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISSION,IZERO,MPI_COMM_WORLD)
	     SCAT_DISP=SCAT_DISP/ATM(ID)%XzVF_F; SCAT_SIZE=SCAT_SIZE/ATM(ID)%XzVF_F
          END IF
        END DO
!
	DEALLOCATE(SCAT_SIZE,SCAT_DISP)
!
	RETURN
	END
