	SUBROUTINE MPI_ERR_CHECK(IERR,MESSAGE)
	USE SET_KIND_MODULE
	INTEGER IERR, LOC_IERR
	CHARACTER(LEN=*) MESSAGE	
!
	IF(IERR .NE. 0)THEN
	  WRITE(6,*)'Error associated with MPI processor',MYPE
	  WRITE(6,*)MESSAGE
	  CALL MPI_ABORT(MPI_COMM_WORLD,ERRORCODE,LOC_IERR)
	  CALL MPI_FINALIZE(LOC_IERR)
	  STOP
	END IF
!
	RETURN
	END
