	SUBROUTINE SEND_OP_ETA_MPI(VCHI,NT,VDST,VDEND,DST,DEND,ND)
	USE SET_KIND_MODULE
	USE MPI
	IMPLICIT NONE
!
	INTEGER ND,NT
	INTEGER DST,DEND
	INTEGER VDST,VDEND
	INTEGER REC_STATUS(MPI_STATUS_SIZE)
	REAL*8 VCHI(NT,VDST:VDEND)
	REAL*8 VALL(NT,ND)
!
	INTEGER, ALLOCATABLE, SAVE :: SCAT_DISP(:)
	INTEGER, ALLOCATABLE, SAVE :: SCAT_SIZE(:)
!
	INTEGER, PARAMETER :: IZERO=0
	INTEGER IERR
	INTEGER ITAG
	INTEGER SEND_MYPE
	INTEGER DEST_MYPE
!
! Changed 10-Jun-2025 (changed 20 to 48).
!
	IF(NTHREAD .GT. 48)THEN
	  IF(.NOT. ALLOCATED(SCAT_DISP))THEN
	    ALLOCATE(SCAT_DISP(0:NTHREAD-1))
	    ALLOCATE(SCAT_SIZE(0:NTHREAD-1))
	  END IF
	  CALL SET_IDISP_ISEND(SCAT_DISP,SCAT_SIZE,ND,NTHREAD)
	  SCAT_DISP=SCAT_DISP*NT; SCAT_SIZE=SCAT_SIZE*NT
	  CALL MPI_ALLGATHERV(VCHI(:,DST:DEND),SCAT_SIZE(MYPE),MPI_DOUBLE_PRECISION,
	1                  VALL,SCAT_SIZE,SCAT_DISP,MPI_DOUBLE_PRECISION,MPI_COMM_WORLD,IERR)
	  VCHI(:,VDST)=VALL(:,VDST)
	  VCHI(:,VDEND)=VALL(:,VDEND)
	ELSE
!
!  Each process computes VCHI from DST to DEND, but for the tridiagonal approach we need to extend to DST-1 and
!  DEND+1 for each process. The approach below may not be the best, but it avoids sync. issues.
!
	  ITAG=0
	  DO SEND_MYPE=1,NTHREAD-1,2
	    DEST_MYPE=SEND_MYPE-1
	    IF(MYPE .EQ. SEND_MYPE)THEN
	      CALL MPI_SEND(VCHI(:,DST),NT,MPI_DOUBLE_PRECISION,DEST_MYPE,ITAG,MPI_COMM_WORLD,IERR)
	    END IF
	    IF(MYPE .EQ. DEST_MYPE)THEN
	      CALL MPI_RECV(VCHI(:,DEND+1),NT,MPI_DOUBLE_PRECISION,SEND_MYPE,ITAG,MPI_COMM_WORLD,REC_STATUS,IERR)
	    END IF
	  END DO
	  CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
!
	  DO SEND_MYPE=2,NTHREAD-1,2
	    DEST_MYPE=SEND_MYPE-1
	    IF(MYPE .EQ. SEND_MYPE)THEN
	      CALL MPI_SEND(VCHI(:,DST),NT,MPI_DOUBLE_PRECISION,DEST_MYPE,ITAG,MPI_COMM_WORLD,IERR)
	    END IF
	    IF(MYPE .EQ. DEST_MYPE)THEN
	      CALL MPI_RECV(VCHI(:,DEND+1),NT,MPI_DOUBLE_PRECISION,SEND_MYPE,ITAG,MPI_COMM_WORLD,REC_STATUS,IERR)
	    END IF
	  END DO
	  CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
!
	  DO SEND_MYPE=0,NTHREAD-2,2
	    DEST_MYPE=SEND_MYPE+1
	    IF(MYPE .EQ. SEND_MYPE)THEN
	      CALL MPI_SEND(VCHI(:,DEND),NT,MPI_DOUBLE_PRECISION,DEST_MYPE,ITAG,MPI_COMM_WORLD,IERR)
	    END IF
	    IF(MYPE .EQ. DEST_MYPE)THEN
	      CALL MPI_RECV(VCHI(:,DST-1),NT,MPI_DOUBLE_PRECISION,SEND_MYPE,ITAG,MPI_COMM_WORLD,REC_STATUS,IERR)
	    END IF
	  END DO
	  CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
!
	  DO SEND_MYPE=1,NTHREAD-2,2
	    DEST_MYPE=SEND_MYPE+1
	    IF(MYPE .EQ. SEND_MYPE)THEN
	      CALL MPI_SEND(VCHI(:,DEND),NT,MPI_DOUBLE_PRECISION,DEST_MYPE,ITAG,MPI_COMM_WORLD,IERR)
	    END IF
	    IF(MYPE .EQ. DEST_MYPE)THEN
	      CALL MPI_RECV(VCHI(:,DST-1),NT,MPI_DOUBLE_PRECISION,SEND_MYPE,ITAG,MPI_COMM_WORLD,REC_STATUS,IERR)
	    END IF
	  END DO
	  CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
	END IF
!
	RETURN
	END
