	SUBROUTINE CHECK_VEC_NAN(VEC,ND,DESC,NAN_PRES)
	USE SET_KIND_MODULE
	IMPLICIT NONE
	INTEGER ND,I
	REAL(KIND=LDP) VEC(ND)
	LOGICAL NAN_PRES
	CHARACTER(LEN=*) DESC
	LOGICAL, SAVE :: FIRST=.TRUE.
	LOGICAL, SAVE :: SKIP=.TRUE.     !FALSE.
!
	IF(SKIP)THEN
	  IF(FIRST .AND. MYPE .EQ. 0)THEN
	    FIRST=.FALSE.
	    WRITE(6,'(//,A)')'Warning -- CHECK_VEC_NAN is swithched off'
	  END IF
	  RETURN
	END IF
!
	WRITE(6,*)'Currently doing the folloing NaN check',MYPE
	WRITE(6,*)TRIM(DESC); FLUSH(UNIT=6)
!
	DO I=1,ND
	  IF(VEC(I) .NE. VEC(I))THEN
	    WRITE(700+MYPE,*)'Error - NaN present for processor:',MYPE,ND,TRIM(DESC)
	    FLUSH(UNIT=700+MYPE)
	    WRITE(700+MYPE,'(I10,5ES14.4)')I,VEC(I)
	    FLUSH(UNIT=700+MYPE)
	    IF(INDEX(DESC,'(STOP)') .NE. 0)STOP
	    NAN_PRES=.TRUE.
	    RETURN
	  END IF
	END DO
	NAN_PRES=.FALSE.
!
	WRITE(6,*)'Done the following NaN check',MYPE
	WRITE(6,*)TRIM(DESC); FLUSH(UNIT=6)
!
	RETURN
	END

