	SUBROUTINE CHECK_VEC_NAN(VEC,ND,DESC,NAN_PRES)
	USE SET_KIND_MODULE
	IMPLICIT NONE
	INTEGER ND,I
	REAL(KIND=LDP) VEC(ND)
	LOGICAL NAN_PRES
	CHARACTER(LEN=*) DESC
!
	DO I=1,ND
	  IF(VEC(I) .NE. VEC(I))THEN
	    WRITE(6,*)'Error - NaN present for ',TRIM(DESC)
	    WRITE(6,'(5ES14.4)')VEC
	    FLUSH(UNIT=6)
	    IF(INDEX(DESC,'(STOP)') .NE. 0)STOP
	    NAN_PRES=.TRUE.
	    RETURN
	  END IF
	END DO
	NAN_PRES=.FALSE.
!
	RETURN
	END

