	MODULE SET_KIND_MODULE
	IMPLICIT NONE
!
	REAL(8), PRIVATE :: KVAR
        INTEGER, PARAMETER :: LDP=KIND(KVAR)
!
!        INTEGER, PARAMETER :: LDP=SELECTED_REAL_KIND(15,3000)
!
	END MODULE SET_KIND_MODULE
	
