	INTEGER, SAVE :: FIRST=.TRUE.
	INTEGER, SAVE :: MYPE
	INTEGER, SAVE :: NTHREAD
	INTEGER, SAVE :: NUM_DEPTHS_PER_THREAD
	INCLUDE 'mpif.h'
!
	INTEGER GET_DEPTH_INDX
	GET_DEPTH_INDX(IPROC,MYPE,NUM_DEPTHS_PER_THREAD)=IPROC+MYPE*NUM_DEPTHS_PER_THREAD
! 
!
	IF(FIRST)THEN
	  FIRST=.FALSE.
	  CALL MPI_COMM_RANK(MPI_COMM_WORLD,MYPE,IERR)
	  CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NTHREAD,IERR)
	  NUM_DEPTHS_PER_THREAD=(ND-1)/NTHREAD+1
	END IF
!
	SUBROUTINE SET_VECTORS_FOR_GTAHERV(ND)
	IMPLICIT NONE
!
	LOGICAL, SAVE :: FIRST=.TRUE.
!
	IF(FIRST)THEN
	  FIRST=.FALSE.
	  CALL MPI_COMM_RANK(MPI_COMM_WORLD,MYPE,IERR)
	  CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NTHREAD,IERR)
	  NUM_DEPTHS_PER_THREAD=(ND-1)/NTHREAD+1
	END IF
!
! If we do this for all threads, we don't need a separate calculiation for each thread to get ISEND
! We simple set ISEND=ROOT_RECV(MYPE).
!
	CNT=0
        ALLOCATE(ROOT_DISP(0:NTHREAD-1))
        ALLOCATE(ROOT_RECV(0:NTHREAD-1))
        DO K=0,NTHREAD-1
          IROOT_DISP(K)=K*NUM_DEPTHS_PER_THREAD
          IF(CNT+NUM_DEPTHS_PER_THREAD .GT. ND)THEN
            ROOT_RECV(K)=ND-CNT
          ELSE
            ROOT_RECV(K)=NUM_DEPTHS_PER_THREAD
            CNT=CNT+NUM_DEPTHS_PER_THREAD
          END IF
        END DO

