	SUBROUTINE RITE_2DJ_ASC_JH(RAD_MOM,NBETA,ND,DESC,LU)
	USE SET_KIND_MODULE
	IMPLICIT NONE
	INTEGER NBETA,ND,LU
	REAL(KIND=LDP) RAD_MOM(NBETA,ND)
	CHARACTER*(*) DESC
	CHARACTER*50 FMT
C
	WRITE(LU,'(/,X,A)')DESC
	WRITE(FMT,'(A,I1,A)')'(X,1P',MIN(NBETA,8),'E16.7)'
	WRITE(LU,FMT)RAD_MOM
C
	RETURN
	END
