!
	SUBROUTINE WRITE_MULTI_FULL_CHI_JH(ND_MULTI,NB_MULTI,NCF_MULTI,R_MULTI,
	1                               FREQ_MULTI,BETA_MULTI,VR_MULTI,
	1                               SIGMA_MULTI,TEMP_MULTI,ESEC_MULTI,
	1                               ETA_MULTI,CHI_MULTI)
        USE SET_KIND_MODULE
	IMPLICIT NONE
!	
	INTEGER ND_MULTI
	INTEGER NB_MULTI
	INTEGER NCF_MULTI
	REAL(KIND=LDP)  R_MULTI(ND_MULTI)
	REAL(KIND=LDP)  FREQ_MULTI(NCF_MULTI)
	REAL(KIND=LDP)  BETA_MULTI(NB_MULTI)
!
! ND, NBETA
!
	REAL(KIND=LDP) VR_MULTI(ND_MULTI,NB_MULTI)
	REAL(KIND=LDP) SIGMA_MULTI(ND_MULTI,NB_MULTI)
	REAL(KIND=LDP) TEMP_MULTI(ND_MULTI,NB_MULTI)
	REAL(KIND=LDP) ESEC_MULTI(ND_MULTI,NB_MULTI)
!
! ND, NBETA, NCF
!
	REAL(KIND=LDP) ETA_MULTI(ND_MULTI,NB_MULTI,NCF_MULTI)
	REAL(KIND=LDP) CHI_MULTI(ND_MULTI,NB_MULTI,NCF_MULTI)
	INTEGER LU,I,J
!
	WRITE(6,*)'Opening 3D_DATA for output'
        WRITE(6,*)'Number of depth points is  ',SHAPE(R_MULTI)
        WRITE(6,*)'Shape of ETA [ND,NB,NCF] is',SHAPE(ETA_MULTI)
!
	CALL GET_LU(LU,'In WRITE_FULL_CHI')
	OPEN(UNIT=LU,FILE='3D_DATA',FORM='UNFORMATTED',ACCESS='SEQUENTIAL',ACTION='WRITE',STATUS='UNKNOWN')
          WRITE(LU)ND_MULTI,NB_MULTI,NCF_MULTI
	  WRITE(LU)(R_MULTI,J=1,NB_MULTI)
	  WRITE(LU)BETA_MULTI
	  WRITE(LU)FREQ_MULTI
	  WRITE(LU)TEMP_MULTI
	  WRITE(LU)VR_MULTI
	  WRITE(LU)SIGMA_MULTI
          WRITE(LU)ESEC_MULTI
          WRITE(LU)CHI_MULTI
          WRITE(LU)ETA_MULTI
        CLOSE(LU)
!
	RETURN
	END
