	MODULE ZM_DATA_MODULE
	USE SET_KIND_MODULE
	IMPLICIT NONE
	TYPE MODEL_INTENSITY
	  INTEGER NCF
	  INTEGER ND
	  REAL(KIND=LDP), ALLOCATABLE :: RJ(:,:)
	  REAL(KIND=LDP), ALLOCATABLE :: NU(:)
	  REAL(KIND=LDP), ALLOCATABLE :: R(:)
	  REAL(KIND=LDP), ALLOCATABLE :: V(:)
	  REAL(KIND=LDP), ALLOCATABLE :: ED(:)
	  REAL(KIND=LDP), ALLOCATABLE :: T(:)
	  REAL(KIND=LDP), ALLOCATABLE :: TAU_ES(:)
	  REAL(KIND=LDP), ALLOCATABLE :: LANG_COORD(:)
	  REAL(KIND=LDP), ALLOCATABLE :: XV(:)
	  LOGICAL RV_PRES
	  LOGICAL :: XV_SET=.FALSE.
	  CHARACTER(LEN=10) DATA_TYPE
	  CHARACTER(LEN=40) FILE_DATE
	  CHARACTER(LEN=80) FILENAME
	END TYPE MODEL_INTENSITY
	INTEGER :: NUM_FILES=0
	TYPE (MODEL_INTENSITY) ZM(10)
	SAVE
	END MODULE ZM_DATA_MODULE
